// Generated by GradientScript - Types added by post-processor

import type { Point2D, Point3D, Quaternion, Point2DGrad, Point3DGrad, QuaternionGrad } from './gradient-types';

export function angle_residual(pointA: Point3D, vertex: Point3D, pointC: Point3D, targetRadians: number) {
  const v1x = pointA.x - vertex.x;
  const v1y = pointA.y - vertex.y;
  const v1z = pointA.z - vertex.z;
  const v2x = pointC.x - vertex.x;
  const v2y = pointC.y - vertex.y;
  const v2z = pointC.z - vertex.z;
  const dot = v1x * v2x + v1y * v2y + v1z * v2z;
  const crossx = v1y * v2z - v1z * v2y;
  const crossy = v1z * v2x - v1x * v2z;
  const crossz = v1x * v2y - v1y * v2x;
  const crossMag = Math.sqrt(crossx * crossx + crossy * crossy + crossz * crossz);
  const angle = Math.atan2(crossMag, dot);
  return angle - targetRadians;
}

export function angle_residual_grad(pointA: Point3D, vertex: Point3D, pointC: Point3D, targetRadians: number) {
  const v1x = pointA.x - vertex.x;
  const v1y = pointA.y - vertex.y;
  const v1z = pointA.z - vertex.z;
  const v2x = pointC.x - vertex.x;
  const v2y = pointC.y - vertex.y;
  const v2z = pointC.z - vertex.z;
  const dot = v1x * v2x + v1y * v2y + v1z * v2z;
  const crossx = v1y * v2z - v1z * v2y;
  const crossy = v1z * v2x - v1x * v2z;
  const crossz = v1x * v2y - v1y * v2x;
  const crossMag = Math.sqrt(crossx * crossx + crossy * crossy + crossz * crossz);
  const angle = Math.atan2(crossMag, dot);
  const value = angle - targetRadians;

  // Gradients
  const _tmp0 = (pointA.x - vertex.x) * (pointC.x - vertex.x) + (pointA.y - vertex.y) * (pointC.y - vertex.y) + (pointA.z - vertex.z) * (pointC.z - vertex.z);
  const _tmp1 = (pointA.x - vertex.x) * (pointC.x - vertex.x) + (pointA.y - vertex.y) * (pointC.y - vertex.y);
  const _tmp2 = (pointA.x - vertex.x) * (pointC.x - vertex.x);
  const _tmp3 = pointA.x - vertex.x;
  const _tmp4 = pointC.x - vertex.x;
  const _tmp5 = (pointA.y - vertex.y) * (pointC.y - vertex.y);
  const _tmp6 = pointA.y - vertex.y;
  const _tmp7 = pointC.y - vertex.y;
  const _tmp8 = (pointA.z - vertex.z) * (pointC.z - vertex.z);
  const _tmp9 = pointA.z - vertex.z;
  const _tmp10 = pointC.z - vertex.z;
  const _tmp11 = (pointA.z - vertex.z) * (pointC.x - vertex.x) - (pointA.x - vertex.x) * (pointC.z - vertex.z);
  const _tmp12 = (pointA.z - vertex.z) * (pointC.x - vertex.x);
  const _tmp13 = (pointA.x - vertex.x) * (pointC.z - vertex.z);
  const _tmp14 = -pointA.y - vertex.y;
  const _tmp15 = (pointA.x - vertex.x) * (pointC.y - vertex.y) - (pointA.y - vertex.y) * (pointC.x - vertex.x);
  const _tmp16 = (pointA.x - vertex.x) * (pointC.y - vertex.y);
  const _tmp17 = (pointA.y - vertex.y) * (pointC.x - vertex.x);
  const _tmp18 = 2 * Math.sqrt(((pointA.y - vertex.y) * (pointC.z - vertex.z) - (pointA.z - vertex.z) * (pointC.y - vertex.y)) * ((pointA.y - vertex.y) * (pointC.z - vertex.z) - (pointA.z - vertex.z) * (pointC.y - vertex.y)) + ((pointA.z - vertex.z) * (pointC.x - vertex.x) - (pointA.x - vertex.x) * (pointC.z - vertex.z)) * ((pointA.z - vertex.z) * (pointC.x - vertex.x) - (pointA.x - vertex.x) * (pointC.z - vertex.z)) + ((pointA.x - vertex.x) * (pointC.y - vertex.y) - (pointA.y - vertex.y) * (pointC.x - vertex.x)) * ((pointA.x - vertex.x) * (pointC.y - vertex.y) - (pointA.y - vertex.y) * (pointC.x - vertex.x)));
  const _tmp19 = Math.sqrt(((pointA.y - vertex.y) * (pointC.z - vertex.z) - (pointA.z - vertex.z) * (pointC.y - vertex.y)) * ((pointA.y - vertex.y) * (pointC.z - vertex.z) - (pointA.z - vertex.z) * (pointC.y - vertex.y)) + ((pointA.z - vertex.z) * (pointC.x - vertex.x) - (pointA.x - vertex.x) * (pointC.z - vertex.z)) * ((pointA.z - vertex.z) * (pointC.x - vertex.x) - (pointA.x - vertex.x) * (pointC.z - vertex.z)) + ((pointA.x - vertex.x) * (pointC.y - vertex.y) - (pointA.y - vertex.y) * (pointC.x - vertex.x)) * ((pointA.x - vertex.x) * (pointC.y - vertex.y) - (pointA.y - vertex.y) * (pointC.x - vertex.x)));
  const _tmp20 = ((pointA.y - vertex.y) * (pointC.z - vertex.z) - (pointA.z - vertex.z) * (pointC.y - vertex.y)) * ((pointA.y - vertex.y) * (pointC.z - vertex.z) - (pointA.z - vertex.z) * (pointC.y - vertex.y)) + ((pointA.z - vertex.z) * (pointC.x - vertex.x) - (pointA.x - vertex.x) * (pointC.z - vertex.z)) * ((pointA.z - vertex.z) * (pointC.x - vertex.x) - (pointA.x - vertex.x) * (pointC.z - vertex.z)) + ((pointA.x - vertex.x) * (pointC.y - vertex.y) - (pointA.y - vertex.y) * (pointC.x - vertex.x)) * ((pointA.x - vertex.x) * (pointC.y - vertex.y) - (pointA.y - vertex.y) * (pointC.x - vertex.x));
  const _tmp21 = ((pointA.y - vertex.y) * (pointC.z - vertex.z) - (pointA.z - vertex.z) * (pointC.y - vertex.y)) * ((pointA.y - vertex.y) * (pointC.z - vertex.z) - (pointA.z - vertex.z) * (pointC.y - vertex.y)) + ((pointA.z - vertex.z) * (pointC.x - vertex.x) - (pointA.x - vertex.x) * (pointC.z - vertex.z)) * ((pointA.z - vertex.z) * (pointC.x - vertex.x) - (pointA.x - vertex.x) * (pointC.z - vertex.z));
  const _tmp22 = ((pointA.y - vertex.y) * (pointC.z - vertex.z) - (pointA.z - vertex.z) * (pointC.y - vertex.y)) * ((pointA.y - vertex.y) * (pointC.z - vertex.z) - (pointA.z - vertex.z) * (pointC.y - vertex.y));
  const _tmp23 = (pointA.y - vertex.y) * (pointC.z - vertex.z) - (pointA.z - vertex.z) * (pointC.y - vertex.y);
  const _tmp24 = (pointA.y - vertex.y) * (pointC.z - vertex.z);
  const _tmp25 = (pointA.z - vertex.z) * (pointC.y - vertex.y);
  const _tmp26 = ((pointA.z - vertex.z) * (pointC.x - vertex.x) - (pointA.x - vertex.x) * (pointC.z - vertex.z)) * ((pointA.z - vertex.z) * (pointC.x - vertex.x) - (pointA.x - vertex.x) * (pointC.z - vertex.z));
  const _tmp27 = ((pointA.x - vertex.x) * (pointC.y - vertex.y) - (pointA.y - vertex.y) * (pointC.x - vertex.x)) * ((pointA.x - vertex.x) * (pointC.y - vertex.y) - (pointA.y - vertex.y) * (pointC.x - vertex.x));
  const _tmp28 = Math.pow(((pointA.x - vertex.x) * (pointC.x - vertex.x) + (pointA.y - vertex.y) * (pointC.y - vertex.y) + (pointA.z - vertex.z) * (pointC.z - vertex.z)), 2) + Math.pow(Math.sqrt(((pointA.y - vertex.y) * (pointC.z - vertex.z) - (pointA.z - vertex.z) * (pointC.y - vertex.y)) * ((pointA.y - vertex.y) * (pointC.z - vertex.z) - (pointA.z - vertex.z) * (pointC.y - vertex.y)) + ((pointA.z - vertex.z) * (pointC.x - vertex.x) - (pointA.x - vertex.x) * (pointC.z - vertex.z)) * ((pointA.z - vertex.z) * (pointC.x - vertex.x) - (pointA.x - vertex.x) * (pointC.z - vertex.z)) + ((pointA.x - vertex.x) * (pointC.y - vertex.y) - (pointA.y - vertex.y) * (pointC.x - vertex.x)) * ((pointA.x - vertex.x) * (pointC.y - vertex.y) - (pointA.y - vertex.y) * (pointC.x - vertex.x))), 2);
  const _tmp29 = Math.pow(((pointA.x - vertex.x) * (pointC.x - vertex.x) + (pointA.y - vertex.y) * (pointC.y - vertex.y) + (pointA.z - vertex.z) * (pointC.z - vertex.z)), 2);
  const _tmp30 = Math.pow(Math.sqrt(((pointA.y - vertex.y) * (pointC.z - vertex.z) - (pointA.z - vertex.z) * (pointC.y - vertex.y)) * ((pointA.y - vertex.y) * (pointC.z - vertex.z) - (pointA.z - vertex.z) * (pointC.y - vertex.y)) + ((pointA.z - vertex.z) * (pointC.x - vertex.x) - (pointA.x - vertex.x) * (pointC.z - vertex.z)) * ((pointA.z - vertex.z) * (pointC.x - vertex.x) - (pointA.x - vertex.x) * (pointC.z - vertex.z)) + ((pointA.x - vertex.x) * (pointC.y - vertex.y) - (pointA.y - vertex.y) * (pointC.x - vertex.x)) * ((pointA.x - vertex.x) * (pointC.y - vertex.y) - (pointA.y - vertex.y) * (pointC.x - vertex.x))), 2);
  const _tmp31 = -pointA.z - vertex.z;
  const _tmp32 = -pointA.x - vertex.x;
  const _tmp33 = -1 * (pointC.x - vertex.x);
  const _tmp34 = (pointA.x - vertex.x) * -1;
  const _tmp35 = Math.pow(((pointA.x - vertex.x) * (pointC.x - vertex.x) + (pointA.y - vertex.y) * (pointC.y - vertex.y) + (pointA.z - vertex.z) * (pointC.z - vertex.z)), 2) + Math.pow(Math.sqrt(((pointA.y - vertex.y) * (pointC.z - vertex.z) - (pointA.z - vertex.z) * (pointC.y - vertex.y)) * ((pointA.y - vertex.y) * (pointC.z - vertex.z) - (pointA.z - vertex.z) * (pointC.y - vertex.y)) + ((pointA.z - vertex.z) * (pointC.x - vertex.x) - (pointA.x - vertex.x) * (pointC.z - vertex.z)) * ((pointA.z - vertex.z) * (pointC.x - vertex.x) - (pointA.x - vertex.x) * (pointC.z - vertex.z)) + ((pointA.x - vertex.x) * (pointC.y - vertex.y) - (pointA.y - vertex.y) * (pointC.x - vertex.x)) * ((pointA.x - vertex.x) * (pointC.y - vertex.y) - (pointA.y - vertex.y) * (pointC.x - vertex.x))), 2);
  const _tmp36 = Math.pow(((pointA.x - vertex.x) * (pointC.x - vertex.x) + (pointA.y - vertex.y) * (pointC.y - vertex.y) + (pointA.z - vertex.z) * (pointC.z - vertex.z)), 2);
  const _tmp37 = Math.pow(Math.sqrt(((pointA.y - vertex.y) * (pointC.z - vertex.z) - (pointA.z - vertex.z) * (pointC.y - vertex.y)) * ((pointA.y - vertex.y) * (pointC.z - vertex.z) - (pointA.z - vertex.z) * (pointC.y - vertex.y)) + ((pointA.z - vertex.z) * (pointC.x - vertex.x) - (pointA.x - vertex.x) * (pointC.z - vertex.z)) * ((pointA.z - vertex.z) * (pointC.x - vertex.x) - (pointA.x - vertex.x) * (pointC.z - vertex.z)) + ((pointA.x - vertex.x) * (pointC.y - vertex.y) - (pointA.y - vertex.y) * (pointC.x - vertex.x)) * ((pointA.x - vertex.x) * (pointC.y - vertex.y) - (pointA.y - vertex.y) * (pointC.x - vertex.x))), 2);
  const _tmp38 = -1 * (pointC.z - vertex.z) - (pointA.z - vertex.z) * -1;
  const _tmp39 = (pointA.x - vertex.x) * -1 - -1 * (pointC.x - vertex.x);
  const _tmp40 = (pointA.y - vertex.y) * -1 - -1 * (pointC.y - vertex.y);
  const _tmp41 = -1 * (pointC.x - vertex.x) - (pointA.x - vertex.x) * -1;

  // Gradient for pointA
  const dpointA = {
    x: (_tmp0 * ((-_tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (-_tmp10) + _tmp7 * (_tmp3 * _tmp7 - _tmp6 * _tmp4) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * _tmp7) / (2 * Math.sqrt((_tmp6 * _tmp10 - _tmp9 * _tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4))) - Math.sqrt((_tmp6 * _tmp10 - _tmp9 * _tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4)) * _tmp4) / (_tmp0 * _tmp0 + Math.pow(Math.sqrt((_tmp6 * _tmp10 - _tmp9 * _tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4)), 2)),
    y: (_tmp0 * (_tmp10 * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp6 * _tmp10 - _tmp9 * _tmp7) * _tmp10 + (-_tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (-_tmp4)) / (2 * Math.sqrt((_tmp6 * _tmp10 - _tmp9 * _tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4))) - Math.sqrt((_tmp6 * _tmp10 - _tmp9 * _tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4)) * _tmp7) / (_tmp0 * _tmp0 + Math.pow(Math.sqrt((_tmp6 * _tmp10 - _tmp9 * _tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4)), 2)),
    z: (_tmp0 * ((-_tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp6 * _tmp10 - _tmp9 * _tmp7) * (-_tmp7) + _tmp4 * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * _tmp4) / (2 * Math.sqrt((_tmp6 * _tmp10 - _tmp9 * _tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4))) - Math.sqrt((_tmp6 * _tmp10 - _tmp9 * _tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4)) * _tmp10) / (_tmp0 * _tmp0 + Math.pow(Math.sqrt((_tmp6 * _tmp10 - _tmp9 * _tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4)), 2)),
  };
  // Gradient for vertex
  const dvertex = {
    x: (_tmp0 * ((_tmp9 * -1 - -1 * _tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (_tmp9 * -1 - -1 * _tmp10) + (-1 * _tmp7 - _tmp6 * -1) * (_tmp3 * _tmp7 - _tmp6 * _tmp4) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (-1 * _tmp7 - _tmp6 * -1)) / (2 * Math.sqrt((_tmp6 * _tmp10 - _tmp9 * _tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4))) - Math.sqrt((_tmp6 * _tmp10 - _tmp9 * _tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4)) * (-1 * _tmp4 + _tmp3 * -1)) / (_tmp0 * _tmp0 + Math.pow(Math.sqrt((_tmp6 * _tmp10 - _tmp9 * _tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4)), 2)),
    y: (_tmp0 * ((-1 * _tmp10 - _tmp9 * -1) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp6 * _tmp10 - _tmp9 * _tmp7) * (-1 * _tmp10 - _tmp9 * -1) + (_tmp3 * -1 - -1 * _tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (_tmp3 * -1 - -1 * _tmp4)) / (2 * Math.sqrt((_tmp6 * _tmp10 - _tmp9 * _tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4))) - Math.sqrt((_tmp6 * _tmp10 - _tmp9 * _tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4)) * (-1 * _tmp7 + _tmp6 * -1)) / (_tmp0 * _tmp0 + Math.pow(Math.sqrt((_tmp6 * _tmp10 - _tmp9 * _tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4)), 2)),
    z: (_tmp0 * ((_tmp6 * -1 - -1 * _tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp6 * _tmp10 - _tmp9 * _tmp7) * (_tmp6 * -1 - -1 * _tmp7) + (-1 * _tmp4 - _tmp3 * -1) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (-1 * _tmp4 - _tmp3 * -1)) / (2 * Math.sqrt((_tmp6 * _tmp10 - _tmp9 * _tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4))) - Math.sqrt((_tmp6 * _tmp10 - _tmp9 * _tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4)) * (-1 * _tmp10 + _tmp9 * -1)) / (_tmp0 * _tmp0 + Math.pow(Math.sqrt((_tmp6 * _tmp10 - _tmp9 * _tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4)), 2)),
  };
  // Gradient for pointC
  const dpointC = {
    x: (_tmp0 * (_tmp9 * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * _tmp9 + (-_tmp6) * (_tmp3 * _tmp7 - _tmp6 * _tmp4) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (-_tmp6)) / (2 * Math.sqrt((_tmp6 * _tmp10 - _tmp9 * _tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4))) - Math.sqrt((_tmp6 * _tmp10 - _tmp9 * _tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4)) * _tmp3) / (_tmp0 * _tmp0 + Math.pow(Math.sqrt((_tmp6 * _tmp10 - _tmp9 * _tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4)), 2)),
    y: (_tmp0 * ((-_tmp9) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp6 * _tmp10 - _tmp9 * _tmp7) * (-_tmp9) + _tmp3 * (_tmp3 * _tmp7 - _tmp6 * _tmp4) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * _tmp3) / (2 * Math.sqrt((_tmp6 * _tmp10 - _tmp9 * _tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4))) - Math.sqrt((_tmp6 * _tmp10 - _tmp9 * _tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4)) * _tmp6) / (_tmp0 * _tmp0 + Math.pow(Math.sqrt((_tmp6 * _tmp10 - _tmp9 * _tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4)), 2)),
    z: (_tmp0 * (_tmp6 * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp6 * _tmp10 - _tmp9 * _tmp7) * _tmp6 + (-_tmp3) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (-_tmp3)) / (2 * Math.sqrt((_tmp6 * _tmp10 - _tmp9 * _tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4))) - Math.sqrt((_tmp6 * _tmp10 - _tmp9 * _tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4)) * _tmp9) / (_tmp0 * _tmp0 + Math.pow(Math.sqrt((_tmp6 * _tmp10 - _tmp9 * _tmp7) * (_tmp6 * _tmp10 - _tmp9 * _tmp7) + (_tmp9 * _tmp4 - _tmp3 * _tmp10) * (_tmp9 * _tmp4 - _tmp3 * _tmp10) + (_tmp3 * _tmp7 - _tmp6 * _tmp4) * (_tmp3 * _tmp7 - _tmp6 * _tmp4)), 2)),
  };

  return {
    value,
    dpointA,
    dvertex,
    dpointC,
  };
}
