// Generated by GradientScript - Types added by post-processor

import type { Point2D, Point3D, Quaternion, Point2DGrad, Point3DGrad, QuaternionGrad } from './gradient-types';

export function coincident_point_x(pA: Point3D, pB: Point3D, pP: Point3D, scale: number) {
  const apy = pP.y - pA.y;
  const apz = pP.z - pA.z;
  const aby = pB.y - pA.y;
  const abz = pB.z - pA.z;
  const crossX = apy * abz - apz * aby;
  return scale * crossX;
}

export function coincident_point_x_grad(pA: Point3D, pB: Point3D, pP: Point3D, scale: number) {
  const apy = pP.y - pA.y;
  const apz = pP.z - pA.z;
  const aby = pB.y - pA.y;
  const abz = pB.z - pA.z;
  const crossX = apy * abz - apz * aby;
  const value = scale * crossX;

  // Gradients
  // Gradient for pA
  const dpA = {
    x: 0,
    y: scale * (-1 * (pB.z - pA.z) - (pP.z - pA.z) * -1),
    z: scale * ((pP.y - pA.y) * -1 - -1 * (pB.y - pA.y)),
  };
  // Gradient for pB
  const dpB = {
    x: 0,
    y: scale * (-pP.z - pA.z),
    z: scale * (pP.y - pA.y),
  };
  // Gradient for pP
  const dpP = {
    x: 0,
    y: scale * (pB.z - pA.z),
    z: scale * (-pB.y - pA.y),
  };

  return {
    value,
    dpA,
    dpB,
    dpP,
  };
}
