// Generated by GradientScript - Types added by post-processor

import type { Point2D, Point3D, Quaternion, Point2DGrad, Point3DGrad, QuaternionGrad } from './gradient-types';

export function coincident_point_y(pA: Point3D, pB: Point3D, pP: Point3D, scale: number) {
  const apx = pP.x - pA.x;
  const apz = pP.z - pA.z;
  const abx = pB.x - pA.x;
  const abz = pB.z - pA.z;
  const crossY = apz * abx - apx * abz;
  return scale * crossY;
}

export function coincident_point_y_grad(pA: Point3D, pB: Point3D, pP: Point3D, scale: number) {
  const apx = pP.x - pA.x;
  const apz = pP.z - pA.z;
  const abx = pB.x - pA.x;
  const abz = pB.z - pA.z;
  const crossY = apz * abx - apx * abz;
  const value = scale * crossY;

  // Gradients
  // Gradient for pA
  const dpA = {
    x: scale * ((pP.z - pA.z) * -1 - -1 * (pB.z - pA.z)),
    y: 0,
    z: scale * (-1 * (pB.x - pA.x) - (pP.x - pA.x) * -1),
  };
  // Gradient for pB
  const dpB = {
    x: scale * (pP.z - pA.z),
    y: 0,
    z: scale * (-pP.x - pA.x),
  };
  // Gradient for pP
  const dpP = {
    x: scale * (-pB.z - pA.z),
    y: 0,
    z: scale * (pB.x - pA.x),
  };

  return {
    value,
    dpA,
    dpB,
    dpP,
  };
}
