// Generated by GradientScript - Types added by post-processor

import type { Point2D, Point3D, Quaternion, Point2DGrad, Point3DGrad, QuaternionGrad } from './gradient-types';

export function coincident_point_z(pA: Point3D, pB: Point3D, pP: Point3D, scale: number) {
  const apx = pP.x - pA.x;
  const apy = pP.y - pA.y;
  const abx = pB.x - pA.x;
  const aby = pB.y - pA.y;
  const crossZ = apx * aby - apy * abx;
  return scale * crossZ;
}

export function coincident_point_z_grad(pA: Point3D, pB: Point3D, pP: Point3D, scale: number) {
  const apx = pP.x - pA.x;
  const apy = pP.y - pA.y;
  const abx = pB.x - pA.x;
  const aby = pB.y - pA.y;
  const crossZ = apx * aby - apy * abx;
  const value = scale * crossZ;

  // Gradients
  // Gradient for pA
  const dpA = {
    x: scale * (-1 * (pB.y - pA.y) - (pP.y - pA.y) * -1),
    y: scale * ((pP.x - pA.x) * -1 - -1 * (pB.x - pA.x)),
    z: 0,
  };
  // Gradient for pB
  const dpB = {
    x: scale * (-pP.y - pA.y),
    y: scale * (pP.x - pA.x),
    z: 0,
  };
  // Gradient for pP
  const dpP = {
    x: scale * (pB.y - pA.y),
    y: scale * (-pB.x - pA.x),
    z: 0,
  };

  return {
    value,
    dpA,
    dpB,
    dpP,
  };
}
