// Generated by GradientScript - Types added by post-processor

import type { Point2D, Point3D, Quaternion, Point2DGrad, Point3DGrad, QuaternionGrad } from './gradient-types';

export function collinear_y(p0: Point3D, p1: Point3D, p2: Point3D) {
  const v1x = p1.x - p0.x;
  const v1z = p1.z - p0.z;
  const v2x = p2.x - p0.x;
  const v2z = p2.z - p0.z;
  return v1z * v2x - v1x * v2z;
}

export function collinear_y_grad(p0: Point3D, p1: Point3D, p2: Point3D) {
  const v1x = p1.x - p0.x;
  const v1z = p1.z - p0.z;
  const v2x = p2.x - p0.x;
  const v2z = p2.z - p0.z;
  const value = v1z * v2x - v1x * v2z;

  // Gradients
  // Gradient for p0
  const dp0 = {
    x: (p1.z - p0.z) * -1 - -1 * (p2.z - p0.z),
    y: 0,
    z: -1 * (p2.x - p0.x) - (p1.x - p0.x) * -1,
  };
  // Gradient for p1
  const dp1 = {
    x: -p2.z - p0.z,
    y: 0,
    z: p2.x - p0.x,
  };
  // Gradient for p2
  const dp2 = {
    x: p1.z - p0.z,
    y: 0,
    z: -p1.x - p0.x,
  };

  return {
    value,
    dp0,
    dp1,
    dp2,
  };
}
