// Generated by GradientScript - Types added by post-processor

import type { Point2D, Point3D, Quaternion, Point2DGrad, Point3DGrad, QuaternionGrad } from './gradient-types';

export function collinear_x(p0: Point3D, p1: Point3D, p2: Point3D) {
  const v1y = p1.y - p0.y;
  const v1z = p1.z - p0.z;
  const v2y = p2.y - p0.y;
  const v2z = p2.z - p0.z;
  return v1y * v2z - v1z * v2y;
}

export function collinear_x_grad(p0: Point3D, p1: Point3D, p2: Point3D) {
  const v1y = p1.y - p0.y;
  const v1z = p1.z - p0.z;
  const v2y = p2.y - p0.y;
  const v2z = p2.z - p0.z;
  const value = v1y * v2z - v1z * v2y;

  // Gradients
  // Gradient for p0
  const dp0 = {
    x: 0,
    y: -1 * (p2.z - p0.z) - (p1.z - p0.z) * -1,
    z: (p1.y - p0.y) * -1 - -1 * (p2.y - p0.y),
  };
  // Gradient for p1
  const dp1 = {
    x: 0,
    y: p2.z - p0.z,
    z: -p2.y - p0.y,
  };
  // Gradient for p2
  const dp2 = {
    x: 0,
    y: -p1.z - p0.z,
    z: p1.y - p0.y,
  };

  return {
    value,
    dp0,
    dp1,
    dp2,
  };
}
