// Generated by GradientScript - Types added by post-processor

import type { Point2D, Point3D, Quaternion, Point2DGrad, Point3DGrad, QuaternionGrad } from './gradient-types';

export function collinear_z(p0: Point3D, p1: Point3D, p2: Point3D) {
  const v1x = p1.x - p0.x;
  const v1y = p1.y - p0.y;
  const v2x = p2.x - p0.x;
  const v2y = p2.y - p0.y;
  return v1x * v2y - v1y * v2x;
}

export function collinear_z_grad(p0: Point3D, p1: Point3D, p2: Point3D) {
  const v1x = p1.x - p0.x;
  const v1y = p1.y - p0.y;
  const v2x = p2.x - p0.x;
  const v2y = p2.y - p0.y;
  const value = v1x * v2y - v1y * v2x;

  // Gradients
  // Gradient for p0
  const dp0 = {
    x: -1 * (p2.y - p0.y) - (p1.y - p0.y) * -1,
    y: (p1.x - p0.x) * -1 - -1 * (p2.x - p0.x),
    z: 0,
  };
  // Gradient for p1
  const dp1 = {
    x: p2.y - p0.y,
    y: -p2.x - p0.x,
    z: 0,
  };
  // Gradient for p2
  const dp2 = {
    x: -p1.y - p0.y,
    y: p1.x - p0.x,
    z: 0,
  };

  return {
    value,
    dp0,
    dp1,
    dp2,
  };
}
