// Generated by GradientScript - Types added by post-processor

import type { Point2D, Point3D, Quaternion, Point2DGrad, Point3DGrad, QuaternionGrad } from './gradient-types';

export function coplanar_residual(p0: Point3D, p1: Point3D, p2: Point3D, p3: Point3D) {
  const v1x = p1.x - p0.x;
  const v1y = p1.y - p0.y;
  const v1z = p1.z - p0.z;
  const v2x = p2.x - p0.x;
  const v2y = p2.y - p0.y;
  const v2z = p2.z - p0.z;
  const v3x = p3.x - p0.x;
  const v3y = p3.y - p0.y;
  const v3z = p3.z - p0.z;
  const cx = v2y * v3z - v2z * v3y;
  const cy = v2z * v3x - v2x * v3z;
  const cz = v2x * v3y - v2y * v3x;
  const scalarTriple = v1x * cx + v1y * cy + v1z * cz;
  const len1 = Math.sqrt(v1x * v1x + v1y * v1y + v1z * v1z);
  const len2 = Math.sqrt(v2x * v2x + v2y * v2y + v2z * v2z);
  const len3 = Math.sqrt(v3x * v3x + v3y * v3y + v3z * v3z);
  const epsilon = 0.000001;
  const normFactor = len1 * len2 * len3 + epsilon;
  return scalarTriple / normFactor;
}

export function coplanar_residual_grad(p0: Point3D, p1: Point3D, p2: Point3D, p3: Point3D) {
  const v1x = p1.x - p0.x;
  const v1y = p1.y - p0.y;
  const v1z = p1.z - p0.z;
  const v2x = p2.x - p0.x;
  const v2y = p2.y - p0.y;
  const v2z = p2.z - p0.z;
  const v3x = p3.x - p0.x;
  const v3y = p3.y - p0.y;
  const v3z = p3.z - p0.z;
  const cx = v2y * v3z - v2z * v3y;
  const cy = v2z * v3x - v2x * v3z;
  const cz = v2x * v3y - v2y * v3x;
  const scalarTriple = v1x * cx + v1y * cy + v1z * cz;
  const len1 = Math.sqrt(v1x * v1x + v1y * v1y + v1z * v1z);
  const len2 = Math.sqrt(v2x * v2x + v2y * v2y + v2z * v2z);
  const len3 = Math.sqrt(v3x * v3x + v3y * v3y + v3z * v3z);
  const epsilon = 0.000001;
  const normFactor = len1 * len2 * len3 + epsilon;
  const value = scalarTriple / normFactor;

  // Gradients
  const _tmp0 = p1.y - p0.y;
  const _tmp1 = p2.z - p0.z;
  const _tmp2 = p1.z - p0.z;
  const _tmp3 = p2.y - p0.y;
  const _tmp4 = Math.sqrt((p1.x - p0.x) * (p1.x - p0.x) + (p1.y - p0.y) * (p1.y - p0.y) + (p1.z - p0.z) * (p1.z - p0.z)) * Math.sqrt((p2.x - p0.x) * (p2.x - p0.x) + (p2.y - p0.y) * (p2.y - p0.y) + (p2.z - p0.z) * (p2.z - p0.z)) * Math.sqrt((p3.x - p0.x) * (p3.x - p0.x) + (p3.y - p0.y) * (p3.y - p0.y) + (p3.z - p0.z) * (p3.z - p0.z)) + 0.000001;
  const _tmp5 = Math.sqrt((p1.x - p0.x) * (p1.x - p0.x) + (p1.y - p0.y) * (p1.y - p0.y) + (p1.z - p0.z) * (p1.z - p0.z)) * Math.sqrt((p2.x - p0.x) * (p2.x - p0.x) + (p2.y - p0.y) * (p2.y - p0.y) + (p2.z - p0.z) * (p2.z - p0.z)) * Math.sqrt((p3.x - p0.x) * (p3.x - p0.x) + (p3.y - p0.y) * (p3.y - p0.y) + (p3.z - p0.z) * (p3.z - p0.z));
  const _tmp6 = Math.sqrt((p1.x - p0.x) * (p1.x - p0.x) + (p1.y - p0.y) * (p1.y - p0.y) + (p1.z - p0.z) * (p1.z - p0.z)) * Math.sqrt((p2.x - p0.x) * (p2.x - p0.x) + (p2.y - p0.y) * (p2.y - p0.y) + (p2.z - p0.z) * (p2.z - p0.z));
  const _tmp7 = Math.sqrt((p1.x - p0.x) * (p1.x - p0.x) + (p1.y - p0.y) * (p1.y - p0.y) + (p1.z - p0.z) * (p1.z - p0.z));
  const _tmp8 = (p1.x - p0.x) * (p1.x - p0.x) + (p1.y - p0.y) * (p1.y - p0.y) + (p1.z - p0.z) * (p1.z - p0.z);
  const _tmp9 = (p1.x - p0.x) * (p1.x - p0.x) + (p1.y - p0.y) * (p1.y - p0.y);
  const _tmp10 = (p1.x - p0.x) * (p1.x - p0.x);
  const _tmp11 = p1.x - p0.x;
  const _tmp12 = (p1.y - p0.y) * (p1.y - p0.y);
  const _tmp13 = (p1.z - p0.z) * (p1.z - p0.z);
  const _tmp14 = Math.sqrt((p2.x - p0.x) * (p2.x - p0.x) + (p2.y - p0.y) * (p2.y - p0.y) + (p2.z - p0.z) * (p2.z - p0.z));
  const _tmp15 = (p2.x - p0.x) * (p2.x - p0.x) + (p2.y - p0.y) * (p2.y - p0.y) + (p2.z - p0.z) * (p2.z - p0.z);
  const _tmp16 = (p2.x - p0.x) * (p2.x - p0.x) + (p2.y - p0.y) * (p2.y - p0.y);
  const _tmp17 = (p2.x - p0.x) * (p2.x - p0.x);
  const _tmp18 = p2.x - p0.x;
  const _tmp19 = (p2.y - p0.y) * (p2.y - p0.y);
  const _tmp20 = (p2.z - p0.z) * (p2.z - p0.z);
  const _tmp21 = Math.sqrt((p3.x - p0.x) * (p3.x - p0.x) + (p3.y - p0.y) * (p3.y - p0.y) + (p3.z - p0.z) * (p3.z - p0.z));
  const _tmp22 = (p3.x - p0.x) * (p3.x - p0.x) + (p3.y - p0.y) * (p3.y - p0.y) + (p3.z - p0.z) * (p3.z - p0.z);
  const _tmp23 = (p3.x - p0.x) * (p3.x - p0.x) + (p3.y - p0.y) * (p3.y - p0.y);
  const _tmp24 = (p3.x - p0.x) * (p3.x - p0.x);
  const _tmp25 = p3.x - p0.x;
  const _tmp26 = (p3.y - p0.y) * (p3.y - p0.y);
  const _tmp27 = p3.y - p0.y;
  const _tmp28 = (p3.z - p0.z) * (p3.z - p0.z);
  const _tmp29 = p3.z - p0.z;
  const _tmp30 = (p1.x - p0.x) * ((p2.y - p0.y) * (p3.z - p0.z) - (p2.z - p0.z) * (p3.y - p0.y)) + (p1.y - p0.y) * ((p2.z - p0.z) * (p3.x - p0.x) - (p2.x - p0.x) * (p3.z - p0.z)) + (p1.z - p0.z) * ((p2.x - p0.x) * (p3.y - p0.y) - (p2.y - p0.y) * (p3.x - p0.x));
  const _tmp31 = (p1.x - p0.x) * ((p2.y - p0.y) * (p3.z - p0.z) - (p2.z - p0.z) * (p3.y - p0.y)) + (p1.y - p0.y) * ((p2.z - p0.z) * (p3.x - p0.x) - (p2.x - p0.x) * (p3.z - p0.z));
  const _tmp32 = (p1.x - p0.x) * ((p2.y - p0.y) * (p3.z - p0.z) - (p2.z - p0.z) * (p3.y - p0.y));
  const _tmp33 = (p2.y - p0.y) * (p3.z - p0.z) - (p2.z - p0.z) * (p3.y - p0.y);
  const _tmp34 = (p2.y - p0.y) * (p3.z - p0.z);
  const _tmp35 = (p2.z - p0.z) * (p3.y - p0.y);
  const _tmp36 = (p1.y - p0.y) * ((p2.z - p0.z) * (p3.x - p0.x) - (p2.x - p0.x) * (p3.z - p0.z));
  const _tmp37 = (p2.z - p0.z) * (p3.x - p0.x) - (p2.x - p0.x) * (p3.z - p0.z);
  const _tmp38 = (p2.z - p0.z) * (p3.x - p0.x);
  const _tmp39 = (p2.x - p0.x) * (p3.z - p0.z);
  const _tmp40 = (p1.z - p0.z) * ((p2.x - p0.x) * (p3.y - p0.y) - (p2.y - p0.y) * (p3.x - p0.x));
  const _tmp41 = (p2.x - p0.x) * (p3.y - p0.y) - (p2.y - p0.y) * (p3.x - p0.x);
  const _tmp42 = (p2.x - p0.x) * (p3.y - p0.y);
  const _tmp43 = (p2.y - p0.y) * (p3.x - p0.x);
  const _tmp44 = 2 * Math.sqrt((p3.x - p0.x) * (p3.x - p0.x) + (p3.y - p0.y) * (p3.y - p0.y) + (p3.z - p0.z) * (p3.z - p0.z));
  const _tmp45 = Math.pow((Math.sqrt((p1.x - p0.x) * (p1.x - p0.x) + (p1.y - p0.y) * (p1.y - p0.y) + (p1.z - p0.z) * (p1.z - p0.z)) * Math.sqrt((p2.x - p0.x) * (p2.x - p0.x) + (p2.y - p0.y) * (p2.y - p0.y) + (p2.z - p0.z) * (p2.z - p0.z)) * Math.sqrt((p3.x - p0.x) * (p3.x - p0.x) + (p3.y - p0.y) * (p3.y - p0.y) + (p3.z - p0.z) * (p3.z - p0.z)) + 0.000001), 2);
  const _tmp46 = (p2.x - p0.x) * (p3.y - p0.y);
  const _tmp47 = (p2.y - p0.y) * (p3.x - p0.x);
  const _tmp48 = 2 * Math.sqrt((p1.x - p0.x) * (p1.x - p0.x) + (p1.y - p0.y) * (p1.y - p0.y) + (p1.z - p0.z) * (p1.z - p0.z));
  const _tmp49 = (p2.x - p0.x) * -1;
  const _tmp50 = 2 * Math.sqrt((p2.x - p0.x) * (p2.x - p0.x) + (p2.y - p0.y) * (p2.y - p0.y) + (p2.z - p0.z) * (p2.z - p0.z));
  const _tmp51 = -1 * (p3.x - p0.x);
  const _tmp52 = 2 * Math.sqrt((p3.x - p0.x) * (p3.x - p0.x) + (p3.y - p0.y) * (p3.y - p0.y) + (p3.z - p0.z) * (p3.z - p0.z));
  const _tmp53 = Math.pow((Math.sqrt((p1.x - p0.x) * (p1.x - p0.x) + (p1.y - p0.y) * (p1.y - p0.y) + (p1.z - p0.z) * (p1.z - p0.z)) * Math.sqrt((p2.x - p0.x) * (p2.x - p0.x) + (p2.y - p0.y) * (p2.y - p0.y) + (p2.z - p0.z) * (p2.z - p0.z)) * Math.sqrt((p3.x - p0.x) * (p3.x - p0.x) + (p3.y - p0.y) * (p3.y - p0.y) + (p3.z - p0.z) * (p3.z - p0.z)) + 0.000001), 2);

  // Gradient for p0
  const dp0 = {
    x: ((-1 * _tmp0 + _tmp7 * (_tmp5 * -1 - -1 * _tmp3) + _tmp10 * (-1 * _tmp6 - _tmp2 * -1)) * (Math.sqrt(_tmp19 + _tmp7 * _tmp7 + _tmp10 * _tmp10) * Math.sqrt(_tmp26 + _tmp2 * _tmp2 + _tmp5 * _tmp5) * Math.sqrt(_tmp33 + _tmp6 * _tmp6 + _tmp3 * _tmp3) + 0.000001) - (_tmp20 * _tmp0 + _tmp7 * (_tmp5 * _tmp34 - _tmp27 * _tmp3) + _tmp10 * (_tmp27 * _tmp6 - _tmp2 * _tmp34)) * (((-1 * _tmp20 + _tmp20 * -1) / (2 * Math.sqrt(_tmp19 + _tmp7 * _tmp7 + _tmp10 * _tmp10)) * Math.sqrt(_tmp26 + _tmp2 * _tmp2 + _tmp5 * _tmp5) + Math.sqrt(_tmp19 + _tmp7 * _tmp7 + _tmp10 * _tmp10) * (-1 * _tmp27 + _tmp27 * -1) / (2 * Math.sqrt(_tmp26 + _tmp2 * _tmp2 + _tmp5 * _tmp5))) * Math.sqrt(_tmp33 + _tmp6 * _tmp6 + _tmp3 * _tmp3) + Math.sqrt(_tmp19 + _tmp7 * _tmp7 + _tmp10 * _tmp10) * Math.sqrt(_tmp26 + _tmp2 * _tmp2 + _tmp5 * _tmp5) * (-1 * _tmp34 + _tmp34 * -1) / (2 * Math.sqrt(_tmp33 + _tmp6 * _tmp6 + _tmp3 * _tmp3)))) / Math.pow((Math.sqrt(_tmp19 + _tmp7 * _tmp7 + _tmp10 * _tmp10) * Math.sqrt(_tmp26 + _tmp2 * _tmp2 + _tmp5 * _tmp5) * Math.sqrt(_tmp33 + _tmp6 * _tmp6 + _tmp3 * _tmp3) + 0.000001), 2),
    y: ((_tmp20 * (-1 * _tmp3 - _tmp5 * -1) + -1 * (_tmp5 * _tmp34 - _tmp27 * _tmp3) + _tmp10 * (_tmp27 * -1 - -1 * _tmp34)) * (Math.sqrt(_tmp19 + _tmp7 * _tmp7 + _tmp10 * _tmp10) * Math.sqrt(_tmp26 + _tmp2 * _tmp2 + _tmp5 * _tmp5) * Math.sqrt(_tmp33 + _tmp6 * _tmp6 + _tmp3 * _tmp3) + 0.000001) - (_tmp20 * _tmp0 + _tmp7 * (_tmp5 * _tmp34 - _tmp27 * _tmp3) + _tmp10 * (_tmp27 * _tmp6 - _tmp2 * _tmp34)) * (((-1 * _tmp7 + _tmp7 * -1) / (2 * Math.sqrt(_tmp19 + _tmp7 * _tmp7 + _tmp10 * _tmp10)) * Math.sqrt(_tmp26 + _tmp2 * _tmp2 + _tmp5 * _tmp5) + Math.sqrt(_tmp19 + _tmp7 * _tmp7 + _tmp10 * _tmp10) * (-1 * _tmp2 + _tmp2 * -1) / (2 * Math.sqrt(_tmp26 + _tmp2 * _tmp2 + _tmp5 * _tmp5))) * Math.sqrt(_tmp33 + _tmp6 * _tmp6 + _tmp3 * _tmp3) + Math.sqrt(_tmp19 + _tmp7 * _tmp7 + _tmp10 * _tmp10) * Math.sqrt(_tmp26 + _tmp2 * _tmp2 + _tmp5 * _tmp5) * (-1 * _tmp6 + _tmp6 * -1) / (2 * Math.sqrt(_tmp33 + _tmp6 * _tmp6 + _tmp3 * _tmp3)))) / Math.pow((Math.sqrt(_tmp19 + _tmp7 * _tmp7 + _tmp10 * _tmp10) * Math.sqrt(_tmp26 + _tmp2 * _tmp2 + _tmp5 * _tmp5) * Math.sqrt(_tmp33 + _tmp6 * _tmp6 + _tmp3 * _tmp3) + 0.000001), 2),
    z: ((_tmp20 * (_tmp2 * -1 - -1 * _tmp6) + _tmp7 * (-1 * _tmp34 - _tmp27 * -1) + -1 * (_tmp27 * _tmp6 - _tmp2 * _tmp34)) * (Math.sqrt(_tmp19 + _tmp7 * _tmp7 + _tmp10 * _tmp10) * Math.sqrt(_tmp26 + _tmp2 * _tmp2 + _tmp5 * _tmp5) * Math.sqrt(_tmp33 + _tmp6 * _tmp6 + _tmp3 * _tmp3) + 0.000001) - (_tmp20 * _tmp0 + _tmp7 * (_tmp5 * _tmp34 - _tmp27 * _tmp3) + _tmp10 * (_tmp27 * _tmp6 - _tmp2 * _tmp34)) * (((-1 * _tmp10 + _tmp10 * -1) / (2 * Math.sqrt(_tmp19 + _tmp7 * _tmp7 + _tmp10 * _tmp10)) * Math.sqrt(_tmp26 + _tmp2 * _tmp2 + _tmp5 * _tmp5) + Math.sqrt(_tmp19 + _tmp7 * _tmp7 + _tmp10 * _tmp10) * (-1 * _tmp5 + _tmp5 * -1) / (2 * Math.sqrt(_tmp26 + _tmp2 * _tmp2 + _tmp5 * _tmp5))) * Math.sqrt(_tmp33 + _tmp6 * _tmp6 + _tmp3 * _tmp3) + Math.sqrt(_tmp19 + _tmp7 * _tmp7 + _tmp10 * _tmp10) * Math.sqrt(_tmp26 + _tmp2 * _tmp2 + _tmp5 * _tmp5) * (-1 * _tmp3 + _tmp3 * -1) / (2 * Math.sqrt(_tmp33 + _tmp6 * _tmp6 + _tmp3 * _tmp3)))) / Math.pow((Math.sqrt(_tmp19 + _tmp7 * _tmp7 + _tmp10 * _tmp10) * Math.sqrt(_tmp26 + _tmp2 * _tmp2 + _tmp5 * _tmp5) * Math.sqrt(_tmp33 + _tmp6 * _tmp6 + _tmp3 * _tmp3) + 0.000001), 2),
  };
  // Gradient for p1
  const dp1 = {
    x: (_tmp0 * (_tmp10 * Math.sqrt(_tmp22 + _tmp2 * _tmp2 + _tmp5 * _tmp5) * Math.sqrt(_tmp29 + _tmp6 * _tmp6 + _tmp3 * _tmp3) + 0.000001) - (_tmp14 * _tmp0 + _tmp16 * (_tmp5 * _tmp30 - _tmp23 * _tmp3) + _tmp18 * (_tmp23 * _tmp6 - _tmp2 * _tmp30)) * (_tmp14 + _tmp14) / (2 * _tmp10) * Math.sqrt(_tmp22 + _tmp2 * _tmp2 + _tmp5 * _tmp5) * Math.sqrt(_tmp29 + _tmp6 * _tmp6 + _tmp3 * _tmp3)) / Math.pow((_tmp10 * Math.sqrt(_tmp22 + _tmp2 * _tmp2 + _tmp5 * _tmp5) * Math.sqrt(_tmp29 + _tmp6 * _tmp6 + _tmp3 * _tmp3) + 0.000001), 2),
    y: ((_tmp5 * _tmp30 - _tmp23 * _tmp3) * (_tmp10 * Math.sqrt(_tmp22 + _tmp2 * _tmp2 + _tmp5 * _tmp5) * Math.sqrt(_tmp29 + _tmp6 * _tmp6 + _tmp3 * _tmp3) + 0.000001) - (_tmp14 * _tmp0 + _tmp16 * (_tmp5 * _tmp30 - _tmp23 * _tmp3) + _tmp18 * (_tmp23 * _tmp6 - _tmp2 * _tmp30)) * (_tmp16 + _tmp16) / (2 * _tmp10) * Math.sqrt(_tmp22 + _tmp2 * _tmp2 + _tmp5 * _tmp5) * Math.sqrt(_tmp29 + _tmp6 * _tmp6 + _tmp3 * _tmp3)) / Math.pow((_tmp10 * Math.sqrt(_tmp22 + _tmp2 * _tmp2 + _tmp5 * _tmp5) * Math.sqrt(_tmp29 + _tmp6 * _tmp6 + _tmp3 * _tmp3) + 0.000001), 2),
    z: ((_tmp23 * _tmp6 - _tmp2 * _tmp30) * (_tmp10 * Math.sqrt(_tmp22 + _tmp2 * _tmp2 + _tmp5 * _tmp5) * Math.sqrt(_tmp29 + _tmp6 * _tmp6 + _tmp3 * _tmp3) + 0.000001) - (_tmp14 * _tmp0 + _tmp16 * (_tmp5 * _tmp30 - _tmp23 * _tmp3) + _tmp18 * (_tmp23 * _tmp6 - _tmp2 * _tmp30)) * (_tmp18 + _tmp18) / (2 * _tmp10) * Math.sqrt(_tmp22 + _tmp2 * _tmp2 + _tmp5 * _tmp5) * Math.sqrt(_tmp29 + _tmp6 * _tmp6 + _tmp3 * _tmp3)) / Math.pow((_tmp10 * Math.sqrt(_tmp22 + _tmp2 * _tmp2 + _tmp5 * _tmp5) * Math.sqrt(_tmp29 + _tmp6 * _tmp6 + _tmp3 * _tmp3) + 0.000001), 2),
  };
  // Gradient for p2
  const dp2 = {
    x: ((_tmp0 * (-_tmp1) + _tmp2 * _tmp3) * (Math.sqrt(_tmp10 + _tmp0 * _tmp0 + _tmp2 * _tmp2) * _tmp14 * Math.sqrt(_tmp26 + _tmp3 * _tmp3 + _tmp1 * _tmp1) + 0.000001) - (_tmp11 * (_tmp20 * _tmp1 - _tmp22 * _tmp3) + _tmp0 * (_tmp22 * _tmp27 - _tmp18 * _tmp1) + _tmp2 * (_tmp18 * _tmp3 - _tmp20 * _tmp27)) * Math.sqrt(_tmp10 + _tmp0 * _tmp0 + _tmp2 * _tmp2) * (_tmp18 + _tmp18) / (2 * _tmp14) * Math.sqrt(_tmp26 + _tmp3 * _tmp3 + _tmp1 * _tmp1)) / Math.pow((Math.sqrt(_tmp10 + _tmp0 * _tmp0 + _tmp2 * _tmp2) * _tmp14 * Math.sqrt(_tmp26 + _tmp3 * _tmp3 + _tmp1 * _tmp1) + 0.000001), 2),
    y: ((_tmp11 * _tmp1 + _tmp2 * (-_tmp27)) * (Math.sqrt(_tmp10 + _tmp0 * _tmp0 + _tmp2 * _tmp2) * _tmp14 * Math.sqrt(_tmp26 + _tmp3 * _tmp3 + _tmp1 * _tmp1) + 0.000001) - (_tmp11 * (_tmp20 * _tmp1 - _tmp22 * _tmp3) + _tmp0 * (_tmp22 * _tmp27 - _tmp18 * _tmp1) + _tmp2 * (_tmp18 * _tmp3 - _tmp20 * _tmp27)) * Math.sqrt(_tmp10 + _tmp0 * _tmp0 + _tmp2 * _tmp2) * (_tmp20 + _tmp20) / (2 * _tmp14) * Math.sqrt(_tmp26 + _tmp3 * _tmp3 + _tmp1 * _tmp1)) / Math.pow((Math.sqrt(_tmp10 + _tmp0 * _tmp0 + _tmp2 * _tmp2) * _tmp14 * Math.sqrt(_tmp26 + _tmp3 * _tmp3 + _tmp1 * _tmp1) + 0.000001), 2),
    z: ((_tmp11 * (-_tmp3) + _tmp0 * _tmp27) * (Math.sqrt(_tmp10 + _tmp0 * _tmp0 + _tmp2 * _tmp2) * _tmp14 * Math.sqrt(_tmp26 + _tmp3 * _tmp3 + _tmp1 * _tmp1) + 0.000001) - (_tmp11 * (_tmp20 * _tmp1 - _tmp22 * _tmp3) + _tmp0 * (_tmp22 * _tmp27 - _tmp18 * _tmp1) + _tmp2 * (_tmp18 * _tmp3 - _tmp20 * _tmp27)) * Math.sqrt(_tmp10 + _tmp0 * _tmp0 + _tmp2 * _tmp2) * (_tmp22 + _tmp22) / (2 * _tmp14) * Math.sqrt(_tmp26 + _tmp3 * _tmp3 + _tmp1 * _tmp1)) / Math.pow((Math.sqrt(_tmp10 + _tmp0 * _tmp0 + _tmp2 * _tmp2) * _tmp14 * Math.sqrt(_tmp26 + _tmp3 * _tmp3 + _tmp1 * _tmp1) + 0.000001), 2),
  };
  // Gradient for p3
  const dp3 = {
    x: ((_tmp0 * _tmp1 + _tmp2 * (-_tmp3)) * (Math.sqrt(_tmp10 + _tmp0 * _tmp0 + _tmp2 * _tmp2) * Math.sqrt(_tmp17 + _tmp3 * _tmp3 + _tmp1 * _tmp1) * _tmp21 + 0.000001) - (_tmp11 * (_tmp3 * _tmp29 - _tmp1 * _tmp27) + _tmp0 * (_tmp1 * _tmp25 - _tmp18 * _tmp29) + _tmp2 * (_tmp18 * _tmp27 - _tmp3 * _tmp25)) * Math.sqrt(_tmp10 + _tmp0 * _tmp0 + _tmp2 * _tmp2) * Math.sqrt(_tmp17 + _tmp3 * _tmp3 + _tmp1 * _tmp1) * (_tmp25 + _tmp25) / (2 * _tmp21)) / Math.pow((Math.sqrt(_tmp10 + _tmp0 * _tmp0 + _tmp2 * _tmp2) * Math.sqrt(_tmp17 + _tmp3 * _tmp3 + _tmp1 * _tmp1) * _tmp21 + 0.000001), 2),
    y: ((_tmp11 * (-_tmp1) + _tmp2 * _tmp18) * (Math.sqrt(_tmp10 + _tmp0 * _tmp0 + _tmp2 * _tmp2) * Math.sqrt(_tmp17 + _tmp3 * _tmp3 + _tmp1 * _tmp1) * _tmp21 + 0.000001) - (_tmp11 * (_tmp3 * _tmp29 - _tmp1 * _tmp27) + _tmp0 * (_tmp1 * _tmp25 - _tmp18 * _tmp29) + _tmp2 * (_tmp18 * _tmp27 - _tmp3 * _tmp25)) * Math.sqrt(_tmp10 + _tmp0 * _tmp0 + _tmp2 * _tmp2) * Math.sqrt(_tmp17 + _tmp3 * _tmp3 + _tmp1 * _tmp1) * (_tmp27 + _tmp27) / (2 * _tmp21)) / Math.pow((Math.sqrt(_tmp10 + _tmp0 * _tmp0 + _tmp2 * _tmp2) * Math.sqrt(_tmp17 + _tmp3 * _tmp3 + _tmp1 * _tmp1) * _tmp21 + 0.000001), 2),
    z: ((_tmp11 * _tmp3 + _tmp0 * (-_tmp18)) * (Math.sqrt(_tmp10 + _tmp0 * _tmp0 + _tmp2 * _tmp2) * Math.sqrt(_tmp17 + _tmp3 * _tmp3 + _tmp1 * _tmp1) * _tmp21 + 0.000001) - (_tmp11 * (_tmp3 * _tmp29 - _tmp1 * _tmp27) + _tmp0 * (_tmp1 * _tmp25 - _tmp18 * _tmp29) + _tmp2 * (_tmp18 * _tmp27 - _tmp3 * _tmp25)) * Math.sqrt(_tmp10 + _tmp0 * _tmp0 + _tmp2 * _tmp2) * Math.sqrt(_tmp17 + _tmp3 * _tmp3 + _tmp1 * _tmp1) * (_tmp29 + _tmp29) / (2 * _tmp21)) / Math.pow((Math.sqrt(_tmp10 + _tmp0 * _tmp0 + _tmp2 * _tmp2) * Math.sqrt(_tmp17 + _tmp3 * _tmp3 + _tmp1 * _tmp1) * _tmp21 + 0.000001), 2),
  };

  return {
    value,
    dp0,
    dp1,
    dp2,
    dp3,
  };
}
