// Generated by GradientScript - Types added by post-processor

import type { Point3D, Point3DGrad } from './gradient-types';

export function coplanar_residual(p0: Point3D, p1: Point3D, p2: Point3D, p3: Point3D) {
  const v1x = p1.x - p0.x;
  const v1y = p1.y - p0.y;
  const v1z = p1.z - p0.z;
  const v2x = p2.x - p0.x;
  const v2y = p2.y - p0.y;
  const v2z = p2.z - p0.z;
  const v3x = p3.x - p0.x;
  const v3y = p3.y - p0.y;
  const v3z = p3.z - p0.z;
  const cx = v2y * v3z - v2z * v3y;
  const cy = v2z * v3x - v2x * v3z;
  const cz = v2x * v3y - v2y * v3x;
  const scalarTriple = v1x * cx + v1y * cy + v1z * cz;
  const len1 = Math.sqrt(v1x * v1x + v1y * v1y + v1z * v1z);
  const len2 = Math.sqrt(v2x * v2x + v2y * v2y + v2z * v2z);
  const len3 = Math.sqrt(v3x * v3x + v3y * v3y + v3z * v3z);
  const epsilon = 0.000001;
  const normFactor = len1 * len2 * len3 + epsilon;
  return scalarTriple / normFactor;
}

export function coplanar_residual_grad(p0: Point3D, p1: Point3D, p2: Point3D, p3: Point3D): {
  value: number;
  dp0: Point3DGrad;
  dp1: Point3DGrad;
  dp2: Point3DGrad;
  dp3: Point3DGrad;
} {
  const v1x = p1.x - p0.x;
  const v1y = p1.y - p0.y;
  const v1z = p1.z - p0.z;
  const v2x = p2.x - p0.x;
  const v2y = p2.y - p0.y;
  const v2z = p2.z - p0.z;
  const v3x = p3.x - p0.x;
  const v3y = p3.y - p0.y;
  const v3z = p3.z - p0.z;
  const cx = v2y * v3z - v2z * v3y;
  const cy = v2z * v3x - v2x * v3z;
  const cz = v2x * v3y - v2y * v3x;
  const scalarTriple = v1x * cx + v1y * cy + v1z * cz;
  const len1 = Math.sqrt(v1x * v1x + v1y * v1y + v1z * v1z);
  const len2 = Math.sqrt(v2x * v2x + v2y * v2y + v2z * v2z);
  const len3 = Math.sqrt(v3x * v3x + v3y * v3y + v3z * v3z);
  const epsilon = 0.000001;
  const normFactor = len1 * len2 * len3 + epsilon;
  const value = scalarTriple / normFactor;

  // Gradients
  const _tmp0 = len1 * len2;
  const _tmp1 = normFactor * normFactor;

  const _inv0 = 1 / _tmp1;
  const _inv1 = 1 / len1;
  const _inv2 = 1 / len2;
  const _inv3 = 1 / len3;

  // Gradient for p0
  const dp0 = {
    x: ((-cx + v1y * (-v2z + v3z) + v1z * (-v3y + v2y)) * normFactor - scalarTriple * (((-v1x) * _inv1 * len2 + len1 * (-v2x) * _inv2) * len3 + _tmp0 * (-v3x) * _inv3)) * _inv0,
    y: ((v1x * (-v3z + v2z) + -cy + v1z * (-v2x + v3x)) * normFactor - scalarTriple * (((-v1y) * _inv1 * len2 + len1 * (-v2y) * _inv2) * len3 + _tmp0 * (-v3y) * _inv3)) * _inv0,
    z: ((v1x * (-v2y + v3y) + v1y * (-v3x + v2x) + -cz) * normFactor - scalarTriple * (((-v1z) * _inv1 * len2 + len1 * (-v2z) * _inv2) * len3 + _tmp0 * (-v3z) * _inv3)) * _inv0,
  };
  // Gradient for p1
  const dp1 = {
    x: (cx * normFactor - scalarTriple * v1x * _inv1 * len2 * len3) * _inv0,
    y: (cy * normFactor - scalarTriple * v1y * _inv1 * len2 * len3) * _inv0,
    z: (cz * normFactor - scalarTriple * v1z * _inv1 * len2 * len3) * _inv0,
  };
  // Gradient for p2
  const dp2 = {
    x: ((v1y * (-v3z) + v1z * v3y) * normFactor - scalarTriple * len1 * v2x * _inv2 * len3) * _inv0,
    y: ((v1x * v3z + v1z * (-v3x)) * normFactor - scalarTriple * len1 * v2y * _inv2 * len3) * _inv0,
    z: ((v1x * (-v3y) + v1y * v3x) * normFactor - scalarTriple * len1 * v2z * _inv2 * len3) * _inv0,
  };
  // Gradient for p3
  const dp3 = {
    x: ((v1y * v2z + v1z * (-v2y)) * normFactor - scalarTriple * _tmp0 * v3x * _inv3) * _inv0,
    y: ((v1x * (-v2z) + v1z * v2x) * normFactor - scalarTriple * _tmp0 * v3y * _inv3) * _inv0,
    z: ((v1x * v2y + v1y * (-v2x)) * normFactor - scalarTriple * _tmp0 * v3z * _inv3) * _inv0,
  };

  return {
    value,
    dp0,
    dp1,
    dp2,
    dp3,
  };
}
