// Generated by GradientScript - Types added by post-processor

import type { Point2D, Point3D, Quaternion, Point2DGrad, Point3DGrad, QuaternionGrad } from './gradient-types';

export function distance_residual(p1: Point3D, p2: Point3D, target: number) {
  const dx = p2.x - p1.x;
  const dy = p2.y - p1.y;
  const dz = p2.z - p1.z;
  const dist = Math.sqrt(dx * dx + dy * dy + dz * dz);
  return (dist - target) / target;
}

export function distance_residual_grad(p1: Point3D, p2: Point3D, target: number) {
  const dx = p2.x - p1.x;
  const dy = p2.y - p1.y;
  const dz = p2.z - p1.z;
  const dist = Math.sqrt(dx * dx + dy * dy + dz * dz);
  const value = (dist - target) / target;

  // Gradients
  const _tmp0 = p2.x - p1.x;
  const _tmp1 = 2 * Math.sqrt((p2.x - p1.x) * (p2.x - p1.x) + (p2.y - p1.y) * (p2.y - p1.y) + (p2.z - p1.z) * (p2.z - p1.z));
  const _tmp2 = Math.sqrt((p2.x - p1.x) * (p2.x - p1.x) + (p2.y - p1.y) * (p2.y - p1.y) + (p2.z - p1.z) * (p2.z - p1.z));
  const _tmp3 = (p2.x - p1.x) * (p2.x - p1.x) + (p2.y - p1.y) * (p2.y - p1.y) + (p2.z - p1.z) * (p2.z - p1.z);
  const _tmp4 = (p2.x - p1.x) * (p2.x - p1.x) + (p2.y - p1.y) * (p2.y - p1.y);
  const _tmp5 = (p2.x - p1.x) * (p2.x - p1.x);
  const _tmp6 = (p2.y - p1.y) * (p2.y - p1.y);
  const _tmp7 = p2.y - p1.y;
  const _tmp8 = (p2.z - p1.z) * (p2.z - p1.z);
  const _tmp9 = p2.z - p1.z;
  const _tmp10 = target * target;

  // Gradient for p1
  const dp1 = {
    x: ((-1 * _tmp0 + _tmp0 * -1) / (2 * Math.sqrt(_tmp0 * _tmp0 + _tmp6 + _tmp8)) * target) / _tmp10,
    y: ((-1 * _tmp7 + _tmp7 * -1) / (2 * Math.sqrt(_tmp0 * _tmp0 + _tmp6 + _tmp8)) * target) / _tmp10,
    z: ((-1 * _tmp9 + _tmp9 * -1) / (2 * Math.sqrt(_tmp0 * _tmp0 + _tmp6 + _tmp8)) * target) / _tmp10,
  };
  // Gradient for p2
  const dp2 = {
    x: ((_tmp0 + _tmp0) / (2 * Math.sqrt(_tmp0 * _tmp0 + _tmp6 + _tmp8)) * target) / _tmp10,
    y: ((_tmp7 + _tmp7) / (2 * Math.sqrt(_tmp0 * _tmp0 + _tmp6 + _tmp8)) * target) / _tmp10,
    z: ((_tmp9 + _tmp9) / (2 * Math.sqrt(_tmp0 * _tmp0 + _tmp6 + _tmp8)) * target) / _tmp10,
  };

  return {
    value,
    dp1,
    dp2,
  };
}
