// Generated by GradientScript - Types added by post-processor

import type { Point2D, Point3D, Quaternion, Point2DGrad, Point3DGrad, QuaternionGrad } from './gradient-types';

export function distortion_u(normalized: Point2D, k1: number, k2: number, k3: number, p1: number, p2: number) {
  const x = normalized.x;
  const y = normalized.y;
  const r2 = x * x + y * y;
  const r4 = r2 * r2;
  const r6 = r4 * r2;
  const radial = 1 + k1 * r2 + k2 * r4 + k3 * r6;
  const tangential = 2 * p1 * x * y + p2 * (r2 + 2 * x * x);
  return x * radial + tangential;
}

export function distortion_u_grad(normalized: Point2D, k1: number, k2: number, k3: number, p1: number, p2: number) {
  const x = normalized.x;
  const y = normalized.y;
  const r2 = x * x + y * y;
  const r4 = r2 * r2;
  const r6 = r4 * r2;
  const radial = 1 + k1 * r2 + k2 * r4 + k3 * r6;
  const tangential = 2 * p1 * x * y + p2 * (r2 + 2 * x * x);
  const value = x * radial + tangential;

  // Gradients
  const _tmp0 = normalized.x * normalized.x + normalized.y * normalized.y;
  const _tmp1 = normalized.x * normalized.x;
  const _tmp2 = normalized.y * normalized.y;
  const _tmp3 = (normalized.x * normalized.x + normalized.y * normalized.y) * (normalized.x * normalized.x + normalized.y * normalized.y);
  const _tmp4 = normalized.x + normalized.x;
  const _tmp5 = (normalized.x + normalized.x) * (normalized.x * normalized.x + normalized.y * normalized.y) + (normalized.x * normalized.x + normalized.y * normalized.y) * (normalized.x + normalized.x);
  const _tmp6 = (normalized.x + normalized.x) * (normalized.x * normalized.x + normalized.y * normalized.y);
  const _tmp7 = (normalized.x * normalized.x + normalized.y * normalized.y) * (normalized.x + normalized.x);
  const _tmp8 = 2 * p1;
  const _tmp9 = 2 * normalized.x;
  const _tmp10 = normalized.y + normalized.y;
  const _tmp11 = (normalized.y + normalized.y) * (normalized.x * normalized.x + normalized.y * normalized.y) + (normalized.x * normalized.x + normalized.y * normalized.y) * (normalized.y + normalized.y);
  const _tmp12 = (normalized.y + normalized.y) * (normalized.x * normalized.x + normalized.y * normalized.y);
  const _tmp13 = (normalized.x * normalized.x + normalized.y * normalized.y) * (normalized.y + normalized.y);

  // Gradient for normalized
  const dnormalized = {
    x: 1 + k1 * _tmp0 + k2 * _tmp0 * _tmp0 + k3 * _tmp0 * _tmp0 * _tmp0 + normalized.x * (k1 * _tmp4 + k2 * (_tmp4 * _tmp0 + _tmp0 * _tmp4) + k3 * ((_tmp4 * _tmp0 + _tmp0 * _tmp4) * _tmp0 + _tmp0 * _tmp0 * _tmp4)) + _tmp8 * normalized.y + p2 * (_tmp4 + _tmp9 + _tmp9),
    y: normalized.x * (k1 * _tmp10 + k2 * (_tmp10 * _tmp0 + _tmp0 * _tmp10) + k3 * ((_tmp10 * _tmp0 + _tmp0 * _tmp10) * _tmp0 + _tmp0 * _tmp0 * _tmp10)) + _tmp8 * normalized.x + p2 * _tmp10,
  };

  return {
    value,
    dnormalized,
  };
}
