// Generated by GradientScript - Types added by post-processor

import type { Point2D, Point3D, Quaternion, Point2DGrad, Point3DGrad, QuaternionGrad } from './gradient-types';

export function distortion_v(normalized: Point2D, k1: number, k2: number, k3: number, p1: number, p2: number) {
  const x = normalized.x;
  const y = normalized.y;
  const r2 = x * x + y * y;
  const r4 = r2 * r2;
  const r6 = r4 * r2;
  const radial = 1 + k1 * r2 + k2 * r4 + k3 * r6;
  const tangential = p1 * (r2 + 2 * y * y) + 2 * p2 * x * y;
  return y * radial + tangential;
}

export function distortion_v_grad(normalized: Point2D, k1: number, k2: number, k3: number, p1: number, p2: number) {
  const x = normalized.x;
  const y = normalized.y;
  const r2 = x * x + y * y;
  const r4 = r2 * r2;
  const r6 = r4 * r2;
  const radial = 1 + k1 * r2 + k2 * r4 + k3 * r6;
  const tangential = p1 * (r2 + 2 * y * y) + 2 * p2 * x * y;
  const value = y * radial + tangential;

  // Gradients
  const _tmp0 = normalized.x + normalized.x;
  const _tmp1 = (normalized.x + normalized.x) * (normalized.x * normalized.x + normalized.y * normalized.y) + (normalized.x * normalized.x + normalized.y * normalized.y) * (normalized.x + normalized.x);
  const _tmp2 = (normalized.x + normalized.x) * (normalized.x * normalized.x + normalized.y * normalized.y);
  const _tmp3 = normalized.x * normalized.x + normalized.y * normalized.y;
  const _tmp4 = normalized.x * normalized.x;
  const _tmp5 = normalized.y * normalized.y;
  const _tmp6 = (normalized.x * normalized.x + normalized.y * normalized.y) * (normalized.x + normalized.x);
  const _tmp7 = (normalized.x * normalized.x + normalized.y * normalized.y) * (normalized.x * normalized.x + normalized.y * normalized.y);
  const _tmp8 = 2 * p2;
  const _tmp9 = normalized.y + normalized.y;
  const _tmp10 = (normalized.y + normalized.y) * (normalized.x * normalized.x + normalized.y * normalized.y) + (normalized.x * normalized.x + normalized.y * normalized.y) * (normalized.y + normalized.y);
  const _tmp11 = (normalized.y + normalized.y) * (normalized.x * normalized.x + normalized.y * normalized.y);
  const _tmp12 = (normalized.x * normalized.x + normalized.y * normalized.y) * (normalized.y + normalized.y);
  const _tmp13 = 2 * normalized.y;

  // Gradient for normalized
  const dnormalized = {
    x: normalized.y * (k1 * _tmp0 + k2 * (_tmp0 * _tmp3 + _tmp3 * _tmp0) + k3 * ((_tmp0 * _tmp3 + _tmp3 * _tmp0) * _tmp3 + _tmp3 * _tmp3 * _tmp0)) + p1 * _tmp0 + _tmp8 * normalized.y,
    y: 1 + k1 * _tmp3 + k2 * _tmp3 * _tmp3 + k3 * _tmp3 * _tmp3 * _tmp3 + normalized.y * (k1 * _tmp9 + k2 * (_tmp9 * _tmp3 + _tmp3 * _tmp9) + k3 * ((_tmp9 * _tmp3 + _tmp3 * _tmp9) * _tmp3 + _tmp3 * _tmp3 * _tmp9)) + p1 * (_tmp9 + _tmp13 + _tmp13) + _tmp8 * normalized.x,
  };

  return {
    value,
    dnormalized,
  };
}
