// Generated by GradientScript - Types added by post-processor

import type { Point2D, Point3D, Quaternion, Point2DGrad, Point3DGrad, QuaternionGrad } from './gradient-types';

export function fixed_point_x(p: Point3D, tx: number) {
  return p.x - tx;
}

export function fixed_point_x_grad(p: Point3D, tx: number) {
  const value = p.x - tx;

  // Gradients
  // Gradient for p
  const dp = {
    x: 1,
    y: 0,
    z: 0,
  };

  return {
    value,
    dp,
  };
}
