// Generated by GradientScript - Types added by post-processor

import type { Point2D, Point3D, Quaternion, Point2DGrad, Point3DGrad, QuaternionGrad } from './gradient-types';

export function fixed_point_y(p: Point3D, ty: number) {
  return p.y - ty;
}

export function fixed_point_y_grad(p: Point3D, ty: number) {
  const value = p.y - ty;

  // Gradients
  // Gradient for p
  const dp = {
    x: 0,
    y: 1,
    z: 0,
  };

  return {
    value,
    dp,
  };
}
