// Generated by GradientScript - Types added by post-processor

import type { Point2D, Point3D, Quaternion, Point2DGrad, Point3DGrad, QuaternionGrad } from './gradient-types';

export function fixed_point_z(p: Point3D, tz: number) {
  return p.z - tz;
}

export function fixed_point_z_grad(p: Point3D, tz: number) {
  const value = p.z - tz;

  // Gradients
  // Gradient for p
  const dp = {
    x: 0,
    y: 0,
    z: 1,
  };

  return {
    value,
    dp,
  };
}
