/**
 * Gradient Functions Module
 *
 * Hand-coded Jacobians generated by gradient-script for use with
 * the explicit Jacobian optimization system.
 *
 * Each .gs file in this directory defines residual functions and
 * gradient-script generates the corresponding _grad functions.
 *
 * To regenerate: run `node add-types.cjs` from this directory
 *
 * Usage:
 *   import { distance_residual_grad } from './gradients/distance-gradient';
 *   const { value, dp1, dp2 } = distance_residual_grad(p1, p2, target);
 */

// Shared types
export type {
  Point2D,
  Point3D,
  Quaternion,
  Point2DGrad,
  Point3DGrad,
  QuaternionGrad,
} from './gradient-types';

// Core math residuals
export * from './distance-gradient';
export * from './fixed-point-x-gradient';
export * from './fixed-point-y-gradient';
export * from './fixed-point-z-gradient';
export * from './angle-gradient';
export * from './collinear-x-gradient';
export * from './collinear-y-gradient';
export * from './collinear-z-gradient';
export * from './coplanar-gradient';
export * from './quat-norm-gradient';

// Line residuals
export * from './line-direction-x-gradient';
export * from './line-direction-x-z-gradient';
export * from './line-direction-y-x-gradient';
export * from './line-direction-y-z-gradient';
export * from './line-direction-z-x-gradient';
export * from './line-direction-z-y-gradient';
export * from './line-direction-xy-gradient';
export * from './line-direction-xz-gradient';
export * from './line-direction-yz-gradient';
export * from './line-length-gradient';
export * from './coincident-point-x-gradient';
export * from './coincident-point-y-gradient';
export * from './coincident-point-z-gradient';

// Camera projection residuals
export * from './quat-rotate-gradient';
export * from './quat-rotate-y-gradient';
export * from './quat-rotate-z-gradient';
export * from './world-to-camera-x-gradient';
export * from './world-to-camera-y-gradient';
export * from './world-to-camera-z-gradient';
export * from './perspective-u-gradient';
export * from './perspective-v-gradient';
export * from './distortion-u-gradient';
export * from './distortion-v-gradient';
export * from './reprojection-u-gradient';
export * from './reprojection-v-gradient';
