// Generated by GradientScript - Types added by post-processor

import type { Point2D, Point3D, Quaternion, Point2DGrad, Point3DGrad, QuaternionGrad } from './gradient-types';

export function line_direction_z_x(pA: Point3D, pB: Point3D, scale: number) {
  const dx = pB.x - pA.x;
  return scale * dx;
}

export function line_direction_z_x_grad(pA: Point3D, pB: Point3D, scale: number) {
  const dx = pB.x - pA.x;
  const value = scale * dx;

  // Gradients
  // Gradient for pA
  const dpA = {
    x: scale * -1,
    y: 0,
    z: 0,
  };
  // Gradient for pB
  const dpB = {
    x: scale,
    y: 0,
    z: 0,
  };

  return {
    value,
    dpA,
    dpB,
  };
}
