// Generated by GradientScript - Types added by post-processor

import type { Point2D, Point3D, Quaternion, Point2DGrad, Point3DGrad, QuaternionGrad } from './gradient-types';

export function line_direction_y_z(pA: Point3D, pB: Point3D, scale: number) {
  const dz = pB.z - pA.z;
  return scale * dz;
}

export function line_direction_y_z_grad(pA: Point3D, pB: Point3D, scale: number) {
  const dz = pB.z - pA.z;
  const value = scale * dz;

  // Gradients
  // Gradient for pA
  const dpA = {
    x: 0,
    y: 0,
    z: scale * -1,
  };
  // Gradient for pB
  const dpB = {
    x: 0,
    y: 0,
    z: scale,
  };

  return {
    value,
    dpA,
    dpB,
  };
}
