// Generated by GradientScript - Types added by post-processor

import type { Point2D, Point3D, Quaternion, Point2DGrad, Point3DGrad, QuaternionGrad } from './gradient-types';

export function line_direction_x_y(pA: Point3D, pB: Point3D, scale: number) {
  const dy = pB.y - pA.y;
  return scale * dy;
}

export function line_direction_x_y_grad(pA: Point3D, pB: Point3D, scale: number) {
  const dy = pB.y - pA.y;
  const value = scale * dy;

  // Gradients
  // Gradient for pA
  const dpA = {
    x: 0,
    y: scale * -1,
    z: 0,
  };
  // Gradient for pB
  const dpB = {
    x: 0,
    y: scale,
    z: 0,
  };

  return {
    value,
    dpA,
    dpB,
  };
}
