// Generated by GradientScript - Types added by post-processor

import type { Point2D, Point3D, Quaternion, Point2DGrad, Point3DGrad, QuaternionGrad } from './gradient-types';

export function line_length(pA: Point3D, pB: Point3D, targetLength: number, scale: number) {
  const dx = pB.x - pA.x;
  const dy = pB.y - pA.y;
  const dz = pB.z - pA.z;
  const dist = Math.sqrt(dx * dx + dy * dy + dz * dz);
  return scale * (dist - targetLength);
}

export function line_length_grad(pA: Point3D, pB: Point3D, targetLength: number, scale: number) {
  const dx = pB.x - pA.x;
  const dy = pB.y - pA.y;
  const dz = pB.z - pA.z;
  const dist = Math.sqrt(dx * dx + dy * dy + dz * dz);
  const value = scale * (dist - targetLength);

  // Gradients
  const _tmp0 = pB.x - pA.x;
  const _tmp1 = 2 * Math.sqrt((pB.x - pA.x) * (pB.x - pA.x) + (pB.y - pA.y) * (pB.y - pA.y) + (pB.z - pA.z) * (pB.z - pA.z));
  const _tmp2 = Math.sqrt((pB.x - pA.x) * (pB.x - pA.x) + (pB.y - pA.y) * (pB.y - pA.y) + (pB.z - pA.z) * (pB.z - pA.z));
  const _tmp3 = (pB.x - pA.x) * (pB.x - pA.x) + (pB.y - pA.y) * (pB.y - pA.y) + (pB.z - pA.z) * (pB.z - pA.z);
  const _tmp4 = (pB.x - pA.x) * (pB.x - pA.x) + (pB.y - pA.y) * (pB.y - pA.y);
  const _tmp5 = (pB.x - pA.x) * (pB.x - pA.x);
  const _tmp6 = (pB.y - pA.y) * (pB.y - pA.y);
  const _tmp7 = pB.y - pA.y;
  const _tmp8 = (pB.z - pA.z) * (pB.z - pA.z);
  const _tmp9 = pB.z - pA.z;

  // Gradient for pA
  const dpA = {
    x: scale * (-1 * _tmp0 + _tmp0 * -1) / (2 * Math.sqrt(_tmp0 * _tmp0 + _tmp6 + _tmp8)),
    y: scale * (-1 * _tmp7 + _tmp7 * -1) / (2 * Math.sqrt(_tmp0 * _tmp0 + _tmp6 + _tmp8)),
    z: scale * (-1 * _tmp9 + _tmp9 * -1) / (2 * Math.sqrt(_tmp0 * _tmp0 + _tmp6 + _tmp8)),
  };
  // Gradient for pB
  const dpB = {
    x: scale * (_tmp0 + _tmp0) / (2 * Math.sqrt(_tmp0 * _tmp0 + _tmp6 + _tmp8)),
    y: scale * (_tmp7 + _tmp7) / (2 * Math.sqrt(_tmp0 * _tmp0 + _tmp6 + _tmp8)),
    z: scale * (_tmp9 + _tmp9) / (2 * Math.sqrt(_tmp0 * _tmp0 + _tmp6 + _tmp8)),
  };

  return {
    value,
    dpA,
    dpB,
  };
}
