// Generated by GradientScript - Types added by post-processor

import type { Point2D, Point3D, Quaternion, Point2DGrad, Point3DGrad, QuaternionGrad } from './gradient-types';

export function perspective_v(camPoint: Point3D, fy: number, cy: number) {
  return fy * camPoint.y / camPoint.z + cy;
}

export function perspective_v_grad(camPoint: Point3D, fy: number, cy: number) {
  const value = fy * camPoint.y / camPoint.z + cy;

  // Gradients
  const _tmp0 = camPoint.z * camPoint.z;

  // Gradient for camPoint
  const dcamPoint = {
    x: 0,
    y: fy * camPoint.z / _tmp0,
    z: fy * (-camPoint.y) / _tmp0,
  };

  return {
    value,
    dcamPoint,
  };
}
