// Generated by GradientScript - Types added by post-processor

import type { Point2D, Point3D, Quaternion, Point2DGrad, Point3DGrad, QuaternionGrad } from './gradient-types';

export function perspective_u(camPoint: Point3D, fx: number, cx: number) {
  return fx * camPoint.x / camPoint.z + cx;
}

export function perspective_u_grad(camPoint: Point3D, fx: number, cx: number) {
  const value = fx * camPoint.x / camPoint.z + cx;

  // Gradients
  const _tmp0 = camPoint.z * camPoint.z;

  // Gradient for camPoint
  const dcamPoint = {
    x: fx * camPoint.z / _tmp0,
    y: 0,
    z: fx * (-camPoint.x) / _tmp0,
  };

  return {
    value,
    dcamPoint,
  };
}
