// Generated by GradientScript - Types added by post-processor

import type { Point2D, Point3D, Quaternion, Point2DGrad, Point3DGrad, QuaternionGrad } from './gradient-types';

export function quat_rotate_y(q: Quaternion, v: Point3D) {
  const cx = q.y * v.z - q.z * v.y;
  const cy = q.z * v.x - q.x * v.z;
  const cz = q.x * v.y - q.y * v.x;
  const dcx = q.y * cz - q.z * cy;
  const dcy = q.z * cx - q.x * cz;
  const dcz = q.x * cy - q.y * cx;
  return v.y + 2 * q.w * cy + 2 * dcy;
}

export function quat_rotate_y_grad(q: Quaternion, v: Point3D) {
  const cx = q.y * v.z - q.z * v.y;
  const cy = q.z * v.x - q.x * v.z;
  const cz = q.x * v.y - q.y * v.x;
  const dcx = q.y * cz - q.z * cy;
  const dcy = q.z * cx - q.x * cz;
  const dcz = q.x * cy - q.y * cx;
  const value = v.y + 2 * q.w * cy + 2 * dcy;

  // Gradients
  const _tmp0 = 2 * q.w;
  const _tmp1 = q.x * v.y;

  // Gradient for q
  const dq = {
    w: 2 * (q.z * v.x - q.x * v.z),
    x: _tmp0 * (-v.z) + 2 * (-_tmp1 - q.y * v.x + _tmp1),
    y: 2 * (q.z * v.z - q.x * (-v.x)),
    z: _tmp0 * v.x + 2 * (q.y * v.z - q.z * v.y + q.z * (-v.y)),
  };
  // Gradient for v
  const dv = {
    x: _tmp0 * q.z + 2 * (-q.x * (-q.y)),
    y: 1 + 2 * (q.z * (-q.z) - q.x * q.x),
    z: _tmp0 * (-q.x) + 2 * q.z * q.y,
  };

  return {
    value,
    dq,
    dv,
  };
}
