// Generated by GradientScript - Types added by post-processor

import type { Point2D, Point3D, Quaternion, Point2DGrad, Point3DGrad, QuaternionGrad } from './gradient-types';

export function quat_rotate_x(q: Quaternion, v: Point3D) {
  const cx = q.y * v.z - q.z * v.y;
  const cy = q.z * v.x - q.x * v.z;
  const cz = q.x * v.y - q.y * v.x;
  const dcx = q.y * cz - q.z * cy;
  const dcy = q.z * cx - q.x * cz;
  const dcz = q.x * cy - q.y * cx;
  return v.x + 2 * q.w * cx + 2 * dcx;
}

export function quat_rotate_x_grad(q: Quaternion, v: Point3D) {
  const cx = q.y * v.z - q.z * v.y;
  const cy = q.z * v.x - q.x * v.z;
  const cz = q.x * v.y - q.y * v.x;
  const dcx = q.y * cz - q.z * cy;
  const dcy = q.z * cx - q.x * cz;
  const dcz = q.x * cy - q.y * cx;
  const value = v.x + 2 * q.w * cx + 2 * dcx;

  // Gradients
  const _tmp0 = 2 * q.w;
  const _tmp1 = q.z * v.x;

  // Gradient for q
  const dq = {
    w: 2 * (q.y * v.z - q.z * v.y),
    x: 2 * (q.y * v.y - q.z * (-v.z)),
    y: _tmp0 * v.z + 2 * (q.x * v.y - q.y * v.x + q.y * (-v.x)),
    z: _tmp0 * (-v.y) + 2 * (-_tmp1 - q.x * v.z + _tmp1),
  };
  // Gradient for v
  const dv = {
    x: 1 + 2 * (q.y * (-q.y) - q.z * q.z),
    y: _tmp0 * (-q.z) + 2 * q.y * q.x,
    z: _tmp0 * q.y + 2 * (-q.z * (-q.x)),
  };

  return {
    value,
    dq,
    dv,
  };
}
