// Generated by GradientScript - Types added by post-processor

import type { Point2D, Point3D, Quaternion, Point2DGrad, Point3DGrad, QuaternionGrad } from './gradient-types';

export function quat_norm_residual(q: Quaternion) {
  return (q.w * q.w + q.x * q.x + q.y * q.y + q.z * q.z) - 1;
}

export function quat_norm_residual_grad(q: Quaternion) {
  const value = (q.w * q.w + q.x * q.x + q.y * q.y + q.z * q.z) - 1;

  // Gradients
  // Gradient for q
  const dq = {
    w: q.w + q.w,
    x: q.x + q.x,
    y: q.y + q.y,
    z: q.z + q.z,
  };

  return {
    value,
    dq,
  };
}
