// Generated by GradientScript - Types added by post-processor

import type { Point2D, Point3D, Quaternion, Point2DGrad, Point3DGrad, QuaternionGrad } from './gradient-types';

export function quat_rotate_z(q: Quaternion, v: Point3D) {
  const cx = q.y * v.z - q.z * v.y;
  const cy = q.z * v.x - q.x * v.z;
  const cz = q.x * v.y - q.y * v.x;
  const dcx = q.y * cz - q.z * cy;
  const dcy = q.z * cx - q.x * cz;
  const dcz = q.x * cy - q.y * cx;
  return v.z + 2 * q.w * cz + 2 * dcz;
}

export function quat_rotate_z_grad(q: Quaternion, v: Point3D) {
  const cx = q.y * v.z - q.z * v.y;
  const cy = q.z * v.x - q.x * v.z;
  const cz = q.x * v.y - q.y * v.x;
  const dcx = q.y * cz - q.z * cy;
  const dcy = q.z * cx - q.x * cz;
  const dcz = q.x * cy - q.y * cx;
  const value = v.z + 2 * q.w * cz + 2 * dcz;

  // Gradients
  const _tmp0 = 2 * q.w;
  const _tmp1 = q.y * v.z;

  // Gradient for q
  const dq = {
    w: 2 * (q.x * v.y - q.y * v.x),
    x: _tmp0 * v.y + 2 * (q.z * v.x - q.x * v.z + q.x * (-v.z)),
    y: _tmp0 * (-v.x) + 2 * (-_tmp1 - q.z * v.y + _tmp1),
    z: 2 * (q.x * v.x - q.y * (-v.y)),
  };
  // Gradient for v
  const dv = {
    x: _tmp0 * (-q.y) + 2 * q.x * q.z,
    y: _tmp0 * q.x + 2 * (-q.y * (-q.z)),
    z: 1 + 2 * (q.x * (-q.x) - q.y * q.y),
  };

  return {
    value,
    dq,
    dv,
  };
}
