// Generated by GradientScript

export function reprojection_v_dcam(
  camX: number, camY: number, camZ: number,
  fy: number, cy: number,
  k1: number, k2: number, k3: number, p1: number, p2: number,
  observedV: number
): number {
  const _tmp0 = 1 / camZ;
  const normX = camX * _tmp0;
  const normY = camY * _tmp0;
  const r2 = normX * normX + normY * normY;
  const r4 = r2 * r2;
  const r6 = r4 * r2;
  const radial = 1 + k1 * r2 + k2 * r4 + k3 * r6;
  const tangY = p1 * (r2 + 2 * normY * normY) + 2 * p2 * normX * normY;
  const distortedY = normY * radial + tangY;
  const v = cy - fy * distortedY;
  return v - observedV;
}

export function reprojection_v_dcam_grad(
  camX: number, camY: number, camZ: number,
  fy: number, cy: number,
  k1: number, k2: number, k3: number, p1: number, p2: number,
  observedV: number
): { value: number; dcamX: number; dcamY: number; dcamZ: number } {
  const _fwd0 = 1 / camZ;
  const normX = camX * _fwd0;
  const normY = camY * _fwd0;
  const r2 = normX * normX + normY * normY;
  const r4 = r2 * r2;
  const r6 = r4 * r2;
  const radial = 1 + k1 * r2 + k2 * r4 + k3 * r6;
  const tangY = p1 * (r2 + 2 * normY * normY) + 2 * p2 * normX * normY;
  const distortedY = normY * radial + tangY;
  const v = cy - fy * distortedY;
  const value = v - observedV;

  // Gradients
  const _tmp0 = 1 / camZ;
  const _tmp1 = _tmp0 * normX;
  const _tmp4 = _tmp0 * normY;
  const _tmp5 = 2 * _tmp4 * r2;
  const _tmp7 = 2 * p2 * normX + radial;
  const _tmp20 = 2 * _tmp1;
  const _tmp2 = _tmp20 * r2;
  const _tmp21 = 1 / (camZ * camZ);
  const _tmp22 = camX * _tmp21;
  const _tmp23 = camY * _tmp21;
  const _tmp24 = _tmp22 * normX;
  const _tmp25 = _tmp23 * normY;
  const _tmp16 = -_tmp24 - _tmp25;
  const _tmp18 = 2 * r2 * _tmp16;

  const dcamX = fy * (-normY * (p2 * _tmp0 * 2 + 2 * (k1 * _tmp1 + k2 * _tmp2) + k3 * 2 * (r2 * _tmp2 + r4 * _tmp1)) + p1 * _tmp20);
  const dcamY = fy * (-normY * (2 * (k1 * _tmp4 + k2 * _tmp5) + k3 * 2 * (r2 * _tmp5 + r4 * _tmp4)) + _tmp0 * _tmp7 + 2 * p1 * _tmp0 * (normY + 2 * normY));
  const dcamZ = fy * (_tmp23 * _tmp7 - (p1 * 2 * (_tmp25 * -3 - _tmp24) + normY * ((2 * (k1 * _tmp16 + k2 * _tmp18) + k3 * 2 * (r2 * _tmp18 + r4 * _tmp16)) - 2 * _tmp22 * p2)));

  return {
    value,
    dcamX,
    dcamY,
    dcamZ,
  };
}
