// Generated by GradientScript v0.3.1

export interface ReprojectionUDcamGradResult {
  value: number;
  dcamX: number;
  dcamY: number;
  dcamZ: number;
}

export function reprojection_u_dcam(
  camX: number,
  camY: number,
  camZ: number,
  fx: number,
  cx: number,
  k1: number,
  k2: number,
  k3: number,
  p1: number,
  p2: number,
  observedU: number
): number {
  const _tmp0 = 1 / camZ;
  const normX = camX * _tmp0;
  const normY = camY * _tmp0;
  const r2 = normX * normX + normY * normY;
  const r4 = r2 * r2;
  const r6 = r4 * r2;
  const radial = 1 + k1 * r2 + k2 * r4 + k3 * r6;
  const tangX = 2 * p1 * normX * normY + p2 * (r2 + 2 * normX * normX);
  const distortedX = normX * radial + tangX;
  const u = fx * distortedX + cx;
  return u - observedU;
}

export function reprojection_u_dcam_grad(
  camX: number,
  camY: number,
  camZ: number,
  fx: number,
  cx: number,
  k1: number,
  k2: number,
  k3: number,
  p1: number,
  p2: number,
  observedU: number
): ReprojectionUDcamGradResult {
  const _fwd0 = 1 / camZ;
  const normX = camX * _fwd0;
  const normY = camY * _fwd0;
  const r2 = normX * normX + normY * normY;
  const r4 = r2 * r2;
  const r6 = r4 * r2;
  const radial = 1 + k1 * r2 + k2 * r4 + k3 * r6;
  const tangX = 2 * p1 * normX * normY + p2 * (r2 + 2 * normX * normX);
  const distortedX = normX * radial + tangX;
  const u = fx * distortedX + cx;
  const value = u - observedU;

  // Gradients
  const _tmp0 = 1 / camZ;
  const _tmp1 = radial + 2 * p1 * normY;
  const _tmp4 = _tmp0 * normX;
  const _tmp5 = 2 * _tmp4 * r2;
  const _tmp8 = _tmp0 * normY;
  const _tmp20 = 2 * _tmp8;
  const _tmp9 = _tmp20 * r2;
  const _tmp21 = 1 / (camZ * camZ);
  const _tmp22 = camX * _tmp21;
  const _tmp23 = camY * _tmp21;
  const _tmp24 = _tmp22 * normX;
  const _tmp25 = _tmp23 * normY;
  const _tmp16 = -_tmp24 - _tmp25;
  const _tmp18 = 2 * r2 * _tmp16;

  const dcamX = fx * (2 * p2 * _tmp0 * (normX + 2 * normX) + _tmp0 * _tmp1 + normX * (2 * (k1 * _tmp4 + k2 * _tmp5) + k3 * 2 * (r2 * _tmp5 + r4 * _tmp4)));
  const dcamY = fx * (p2 * _tmp20 + normX * (2 * (k1 * _tmp8 + k2 * _tmp9) + k3 * 2 * (r2 * _tmp9 + r4 * _tmp8) + p1 * _tmp0 * 2));
  const dcamZ = fx * (p2 * 2 * (_tmp24 * -3 - _tmp25) + normX * ((2 * (k1 * _tmp16 + k2 * _tmp18) + k3 * 2 * (r2 * _tmp18 + r4 * _tmp16)) - p1 * _tmp23 * 2) - _tmp22 * _tmp1);

  return {
    value,
    dcamX,
    dcamY,
    dcamZ,
  };
}
