// Generated by GradientScript - Types added by post-processor

import type { Point2D, Point3D, Quaternion, Point2DGrad, Point3DGrad, QuaternionGrad } from './gradient-types';

export function world_to_camera_x(worldPoint: Point3D, cameraPos: Point3D, q: Quaternion) {
  const tx = worldPoint.x - cameraPos.x;
  const ty = worldPoint.y - cameraPos.y;
  const tz = worldPoint.z - cameraPos.z;
  const cx = q.y * tz - q.z * ty;
  const cy = q.z * tx - q.x * tz;
  const cz = q.x * ty - q.y * tx;
  const dcx = q.y * cz - q.z * cy;
  const dcy = q.z * cx - q.x * cz;
  const dcz = q.x * cy - q.y * cx;
  return tx + 2 * q.w * cx + 2 * dcx;
}

export function world_to_camera_x_grad(worldPoint: Point3D, cameraPos: Point3D, q: Quaternion) {
  const tx = worldPoint.x - cameraPos.x;
  const ty = worldPoint.y - cameraPos.y;
  const tz = worldPoint.z - cameraPos.z;
  const cx = q.y * tz - q.z * ty;
  const cy = q.z * tx - q.x * tz;
  const cz = q.x * ty - q.y * tx;
  const dcx = q.y * cz - q.z * cy;
  const dcy = q.z * cx - q.x * cz;
  const dcz = q.x * cy - q.y * cx;
  const value = tx + 2 * q.w * cx + 2 * dcx;

  // Gradients
  const _tmp0 = worldPoint.z - cameraPos.z;
  const _tmp1 = worldPoint.y - cameraPos.y;
  const _tmp2 = 2 * q.w;
  const _tmp3 = worldPoint.x - cameraPos.x;
  const _tmp4 = q.z * (worldPoint.x - cameraPos.x);

  // Gradient for worldPoint
  const dworldPoint = {
    x: 1 + 2 * (q.y * (-q.y) - q.z * q.z),
    y: _tmp0 * (-q.z) + 2 * q.y * q.x,
    z: _tmp0 * q.y + 2 * (-q.z * (-q.x)),
  };
  // Gradient for cameraPos
  const dcameraPos = {
    x: -1 + 2 * (q.y * (-_tmp0) - q.z * _tmp1),
    y: _tmp2 * (-_tmp1) + 2 * q.y * _tmp3,
    z: _tmp2 * _tmp0 + 2 * (-q.z * (-_tmp3)),
  };
  // Gradient for q
  const dq = {
    w: 2 * (q.y * _tmp0 - q.z * _tmp1),
    x: 2 * (q.y * _tmp1 - q.z * (-_tmp0)),
    y: _tmp2 * _tmp0 + 2 * (q.x * _tmp1 - q.y * _tmp3 + q.y * (-_tmp3)),
    z: _tmp2 * (-_tmp1) + 2 * (-q.z * _tmp3 - q.x * _tmp0 + q.z * _tmp3),
  };

  return {
    value,
    dworldPoint,
    dcameraPos,
    dq,
  };
}
