// Generated by GradientScript - Types added by post-processor

import type { Point2D, Point3D, Quaternion, Point2DGrad, Point3DGrad, QuaternionGrad } from './gradient-types';

export function world_to_camera_z(worldPoint: Point3D, cameraPos: Point3D, q: Quaternion) {
  const tx = worldPoint.x - cameraPos.x;
  const ty = worldPoint.y - cameraPos.y;
  const tz = worldPoint.z - cameraPos.z;
  const cx = q.y * tz - q.z * ty;
  const cy = q.z * tx - q.x * tz;
  const cz = q.x * ty - q.y * tx;
  const dcx = q.y * cz - q.z * cy;
  const dcy = q.z * cx - q.x * cz;
  const dcz = q.x * cy - q.y * cx;
  return tz + 2 * q.w * cz + 2 * dcz;
}

export function world_to_camera_z_grad(worldPoint: Point3D, cameraPos: Point3D, q: Quaternion) {
  const tx = worldPoint.x - cameraPos.x;
  const ty = worldPoint.y - cameraPos.y;
  const tz = worldPoint.z - cameraPos.z;
  const cx = q.y * tz - q.z * ty;
  const cy = q.z * tx - q.x * tz;
  const cz = q.x * ty - q.y * tx;
  const dcx = q.y * cz - q.z * cy;
  const dcy = q.z * cx - q.x * cz;
  const dcz = q.x * cy - q.y * cx;
  const value = tz + 2 * q.w * cz + 2 * dcz;

  // Gradients
  const _tmp0 = worldPoint.y - cameraPos.y;
  const _tmp1 = worldPoint.x - cameraPos.x;
  const _tmp2 = 2 * q.w;
  const _tmp3 = worldPoint.z - cameraPos.z;
  const _tmp4 = q.y * (worldPoint.z - cameraPos.z);

  // Gradient for worldPoint
  const dworldPoint = {
    x: _tmp0 * (-q.y) + 2 * q.x * q.z,
    y: _tmp0 * q.x + 2 * (-q.y * (-q.z)),
    z: 1 + 2 * (q.x * (-q.x) - q.y * q.y),
  };
  // Gradient for cameraPos
  const dcameraPos = {
    x: _tmp0 * (-_tmp1) + 2 * q.x * _tmp2,
    y: _tmp0 * _tmp3 + 2 * (-q.y * (-_tmp2)),
    z: -1 + 2 * (q.x * (-_tmp3) - q.y * _tmp1),
  };
  // Gradient for q
  const dq = {
    w: 2 * (q.x * _tmp0 - q.y * _tmp1),
    x: _tmp2 * _tmp0 + 2 * (q.z * _tmp1 - q.x * _tmp3 + q.x * (-_tmp3)),
    y: _tmp2 * (-_tmp1) + 2 * (-q.y * _tmp3 - q.z * _tmp0 + q.y * _tmp3),
    z: 2 * (q.x * _tmp1 - q.y * (-_tmp0)),
  };

  return {
    value,
    dworldPoint,
    dcameraPos,
    dq,
  };
}
