// Generated by GradientScript - Types added by post-processor

import type { Point2D, Point3D, Quaternion, Point2DGrad, Point3DGrad, QuaternionGrad } from './gradient-types';

export function world_to_camera_y(worldPoint: Point3D, cameraPos: Point3D, q: Quaternion) {
  const tx = worldPoint.x - cameraPos.x;
  const ty = worldPoint.y - cameraPos.y;
  const tz = worldPoint.z - cameraPos.z;
  const cx = q.y * tz - q.z * ty;
  const cy = q.z * tx - q.x * tz;
  const cz = q.x * ty - q.y * tx;
  const dcx = q.y * cz - q.z * cy;
  const dcy = q.z * cx - q.x * cz;
  const dcz = q.x * cy - q.y * cx;
  return ty + 2 * q.w * cy + 2 * dcy;
}

export function world_to_camera_y_grad(worldPoint: Point3D, cameraPos: Point3D, q: Quaternion) {
  const tx = worldPoint.x - cameraPos.x;
  const ty = worldPoint.y - cameraPos.y;
  const tz = worldPoint.z - cameraPos.z;
  const cx = q.y * tz - q.z * ty;
  const cy = q.z * tx - q.x * tz;
  const cz = q.x * ty - q.y * tx;
  const dcx = q.y * cz - q.z * cy;
  const dcy = q.z * cx - q.x * cz;
  const dcz = q.x * cy - q.y * cx;
  const value = ty + 2 * q.w * cy + 2 * dcy;

  // Gradients
  const _tmp0 = worldPoint.x - cameraPos.x;
  const _tmp1 = worldPoint.z - cameraPos.z;
  const _tmp2 = 2 * q.w;
  const _tmp3 = q.x * (worldPoint.y - cameraPos.y);
  const _tmp4 = worldPoint.y - cameraPos.y;

  // Gradient for worldPoint
  const dworldPoint = {
    x: _tmp0 * q.z + 2 * (-q.x * (-q.y)),
    y: 1 + 2 * (q.z * (-q.z) - q.x * q.x),
    z: _tmp0 * (-q.x) + 2 * q.z * q.y,
  };
  // Gradient for cameraPos
  const dcameraPos = {
    x: _tmp0 * _tmp1 + 2 * (-q.x * (-_tmp2)),
    y: -1 + 2 * (q.z * (-_tmp1) - q.x * _tmp3),
    z: _tmp0 * (-_tmp3) + 2 * q.z * _tmp2,
  };
  // Gradient for q
  const dq = {
    w: 2 * (q.z * _tmp0 - q.x * _tmp1),
    x: _tmp2 * (-_tmp1) + 2 * (-_tmp3 - q.y * _tmp0 + _tmp3),
    y: 2 * (q.z * _tmp1 - q.x * (-_tmp0)),
    z: _tmp2 * _tmp0 + 2 * (q.y * _tmp1 - q.z * _tmp4 + q.z * (-_tmp4)),
  };

  return {
    value,
    dworldPoint,
    dcameraPos,
    dq,
  };
}
