"""Core data models for Pictorigo backend."""

from .constraints import (
    CONSTRAINT_CLASSES,
    AngleConstraint,
    CollinearPointsConstraint,
    CoplanarPointsConstraint,
    DistanceConstraint,
    EqualAnglesConstraint,
    EqualDistancesConstraint,
    FixedPointConstraint,
    ImagePointConstraint,
    ParallelLinesConstraint,
    PerpendicularLinesConstraint,
    convert_frontend_constraint_to_backend,
    create_constraint_from_type,
)
from .entities import (
    CONSTRAINT_STATUS_TYPES,
    CONSTRAINT_TYPES,
    Camera,
    CameraExtrinsics,
    CameraIntrinsics,
    CameraLockFlags,
    Constraint,
    Image,
    ImagePoint,
    Line,
    Plane,
    WorldPoint,
)
from .project import (
    CoordinateSystem,
    GroundPlane,
    OptimizationInfo,
    PointGroup,
    Project,
    ProjectHistoryEntry,
    ProjectSettings,
    SolveResult,
)

__all__ = [
    # Entities
    "WorldPoint",
    "ImagePoint",
    "Image",
    "Camera",
    "CameraIntrinsics",
    "CameraExtrinsics",
    "CameraLockFlags",
    "Line",
    "Plane",
    "Constraint",
    "CONSTRAINT_TYPES",
    "CONSTRAINT_STATUS_TYPES",
    # Project
    "Project",
    "ProjectSettings",
    "PointGroup",
    "GroundPlane",
    "ProjectHistoryEntry",
    "SolveResult",
    "OptimizationInfo",
    "CoordinateSystem",
    # Constraints
    "ImagePointConstraint",
    "DistanceConstraint",
    "AngleConstraint",
    "ParallelLinesConstraint",
    "PerpendicularLinesConstraint",
    "FixedPointConstraint",
    "CollinearPointsConstraint",
    "CoplanarPointsConstraint",
    "EqualDistancesConstraint",
    "EqualAnglesConstraint",
    "CONSTRAINT_CLASSES",
    "create_constraint_from_type",
    "convert_frontend_constraint_to_backend",
]
